name: Install dependencies

description: Install dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      name: Install Node.js
      with:
        node-version: "22"
        registry-url: "https://npm.pkg.github.com"
        scope: "@companionintelligence"

    - uses: pnpm/action-setup@v4
      name: Install pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      shell: bash
      run: pnpm run build
