/** Short, plain-language hints for Tauri startup service rows (keyed by Docker container name). */
export const STARTUP_SERVICE_HINTS: Record<string, string> = {
  'ci-hub-db': 'STARTUP_SERVICE_HINT_DB',
  'ci-os-hub-queue': 'STARTUP_SERVICE_HINT_QUEUE',
  'ci-os-hub': 'STARTUP_SERVICE_HINT_HUB',
  traefik: 'STARTUP_SERVICE_HINT_TRAEFIK',
  'hub-tailscale': 'STARTUP_SERVICE_HINT_TAILSCALE',
  cloudflared: 'STARTUP_SERVICE_HINT_CLOUDFLARED',
  'host-ollama': 'STARTUP_SERVICE_HINT_OLLAMA',
};

export const STARTUP_PROGRESS_HINT = 'STARTUP_PROGRESS_HINT';
export const STARTUP_IMAGE_PULL_HINT = 'STARTUP_IMAGE_PULL_HINT';

export const DOCKER_REQUIRED_HINT = 'DOCKER_REQUIRED_HINT';
export const DOCKER_MAC_ARCH_HINT = 'DOCKER_MAC_ARCH_HINT';
export const DOCKER_DAEMON_HINT = 'DOCKER_DAEMON_HINT';

export const REGISTRATION_DEVICE_ID_HINT = 'REGISTRATION_DEVICE_ID_HINT';
export const REGISTRATION_PAIRING_CODE_HINT = 'REGISTRATION_PAIRING_CODE_HINT';
export const REGISTRATION_ACCOUNT_HINT = 'REGISTRATION_ACCOUNT_HINT';
export const REGISTRATION_PROVISIONING_HINT = 'REGISTRATION_PROVISIONING_HINT';
export const REGISTRATION_DNS_HINT = 'REGISTRATION_DNS_HINT';

export const ONBOARDING_REMOTE_VPN_HINT = 'ONBOARDING_REMOTE_VPN_HINT';
export const ONBOARDING_REMOTE_WEB_HINT = 'ONBOARDING_REMOTE_WEB_HINT';
export const ONBOARDING_BACKEND_OLLAMA_HINT = 'ONBOARDING_BACKEND_OLLAMA_HINT';
export const ONBOARDING_BACKEND_VLLM_HINT = 'ONBOARDING_BACKEND_VLLM_HINT';
export const ONBOARDING_BACKEND_LEMONADE_HINT = 'ONBOARDING_BACKEND_LEMONADE_HINT';
export const ONBOARDING_BACKEND_SPECULATIVE_HINT = 'ONBOARDING_BACKEND_SPECULATIVE_HINT';
