import i18next from 'i18next';

/** Short, plain-language hints for Tauri startup service rows (keyed by Docker container name). */
export const STARTUP_SERVICE_HINTS: Record<string, string> = {
  'ci-hub-db': i18next.t('STARTUP_SERVICE_HINT_DB'),
  'ci-os-hub-queue': i18next.t('STARTUP_SERVICE_HINT_QUEUE'),
  'ci-os-hub': i18next.t('STARTUP_SERVICE_HINT_HUB'),
  traefik: i18next.t('STARTUP_SERVICE_HINT_TRAEFIK'),
  'hub-tailscale': i18next.t('STARTUP_SERVICE_HINT_TAILSCALE'),
  cloudflared: i18next.t('STARTUP_SERVICE_HINT_CLOUDFLARED'),
  'ci-hub-ollama': i18next.t('STARTUP_SERVICE_HINT_OLLAMA'),
};

export const STARTUP_PROGRESS_HINT = i18next.t('STARTUP_PROGRESS_HINT');
export const STARTUP_IMAGE_PULL_HINT = i18next.t('STARTUP_IMAGE_PULL_HINT');

export const DOCKER_REQUIRED_HINT = i18next.t('DOCKER_REQUIRED_HINT');
export const DOCKER_MAC_ARCH_HINT = i18next.t('DOCKER_MAC_ARCH_HINT');
export const DOCKER_DAEMON_HINT = i18next.t('DOCKER_DAEMON_HINT');

export const REGISTRATION_DEVICE_ID_HINT = i18next.t('REGISTRATION_DEVICE_ID_HINT');
export const REGISTRATION_PAIRING_CODE_HINT = i18next.t('REGISTRATION_PAIRING_CODE_HINT');
export const REGISTRATION_ACCOUNT_HINT = i18next.t('REGISTRATION_ACCOUNT_HINT');
export const REGISTRATION_PROVISIONING_HINT = i18next.t('REGISTRATION_PROVISIONING_HINT');
export const REGISTRATION_DNS_HINT = i18next.t('REGISTRATION_DNS_HINT');

export const ONBOARDING_REMOTE_VPN_HINT = i18next.t('ONBOARDING_REMOTE_VPN_HINT');
export const ONBOARDING_REMOTE_WEB_HINT = i18next.t('ONBOARDING_REMOTE_WEB_HINT');
export const ONBOARDING_BACKEND_OLLAMA_HINT = i18next.t('ONBOARDING_BACKEND_OLLAMA_HINT');
export const ONBOARDING_BACKEND_VLLM_HINT = i18next.t('ONBOARDING_BACKEND_VLLM_HINT');
export const ONBOARDING_BACKEND_LEMONADE_HINT = i18next.t('ONBOARDING_BACKEND_LEMONADE_HINT');
export const ONBOARDING_HW_TIER_HINT = i18next.t('ONBOARDING_HW_TIER_HINT');
export const ONBOARDING_HW_UNIFIED_MEMORY_HINT = i18next.t('ONBOARDING_HW_UNIFIED_MEMORY_HINT');
