#!/bin/sh
# CI Hub OpenClaw entrypoint — auto-configures the gateway to use
# Hub-managed inference so the onboarding wizard is skipped entirely.
#
# Distributed via two paths:
#   1. Marketplace app listing — preferred path; copied into /data volume
#      by the Hub install pipeline (copyDataDir).
#   2. Backend bundle fallback — bundled with packages/backend via build.ts
#      and written by install-app-command.ts when the app payload is missing
#      the file (e.g. copyDataDir was skipped because app-data already exists).
#
# Environment variables consumed:
#   OLLAMA_HOST                — Ollama container URL (injected by Hub); its /v1 is OpenAI-compatible
#   OPENCLAW_DATA_DIR          — state directory (default: /data/.openclaw)
#   OPENCLAW_GATEWAY_TOKEN     — gateway auth token (auto-generated by Hub form field)
#   CLAWDBOT_GATEWAY_TOKEN     — legacy gateway token env var (fallback)
#
# If openclaw.json already exists (user has configured OpenClaw), this
# script is a no-op and falls through to the upstream setup-server.

set -e

STATE_DIR="${OPENCLAW_DATA_DIR:-${OPENCLAW_STATE_DIR:-/data/.openclaw}}"
CONFIG_FILE="${STATE_DIR}/openclaw.json"
ENV_FILE="${STATE_DIR}/.env"

# Apps talk to the Ollama container directly (its OpenAI-compatible /v1) — the Hub
# no longer proxies inference. OLLAMA_HOST is injected by the Hub for every app.
INFERENCE_URL="${OLLAMA_HOST:-http://ci-hub-ollama:11434}"
INFERENCE_URL="${INFERENCE_URL%/}/v1"

# ── Auto-configure only on first run ────────────────────────────────────
if [ -n "${OLLAMA_HOST}" ] && [ ! -f "${CONFIG_FILE}" ]; then
  echo "CI Hub: auto-configuring OpenClaw with direct inference endpoint ${INFERENCE_URL}"

  # Ensure directories
  mkdir -p "${STATE_DIR}/workspace" "${STATE_DIR}/agents/main/sessions"

  # Use the Hub-generated gateway token (from form field), or generate one
  GATEWAY_TOKEN="${OPENCLAW_GATEWAY_TOKEN:-${CLAWDBOT_GATEWAY_TOKEN:-$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')}}"

  # ── Discover models from the Hub inference API ──────────────────────────
  # Build the models JSON array by querying the Hub's OpenAI-compatible
  # models endpoint. INFERENCE_URL already includes /v1, so this fetches
  # ${INFERENCE_URL}/models (i.e. /v1/models). Falls back to a single
  # "auto" entry if the Hub isn't reachable yet.
  MODELS_JSON=""
  MODELS_MAP="{}"
  if command -v node >/dev/null 2>&1; then
    MODELS_JSON=$(node -e "
      fetch('${INFERENCE_URL}/models')
        .then(r => r.json())
        .then(d => {
          const text = (d.data || []).filter(m => (m.modality || []).includes('text'));
          const models = [
            {
              id: 'auto',
              name: 'Hub Auto (best available)',
              reasoning: false,
              input: ['text'],
              cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
              contextWindow: 32000,
              maxTokens: 4096
            },
            ...text.map(m => ({
              id: m.id,
              name: m.id,
              reasoning: false,
              input: ['text'],
              cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
              contextWindow: m.context_window || 32000,
              maxTokens: m.max_tokens || 4096
            }))
          ];
          const map = {};
          models.forEach(m => { map['ci-hub/' + m.id] = {}; });
          console.log(JSON.stringify({ models, map }));
        })
        .catch(() => {
          console.log(JSON.stringify({
            models: [{
              id: 'auto', name: 'Hub Auto (best available)', reasoning: false,
              input: ['text'],
              cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
              contextWindow: 32000, maxTokens: 4096
            }],
            map: { 'ci-hub/auto': {} }
          }));
        });
    " 2>/dev/null) || true
  fi

  # Fallback if node fetch failed or returned empty
  if [ -z "${MODELS_JSON}" ]; then
    MODELS_JSON='{"models":[{"id":"auto","name":"Hub Auto (best available)","reasoning":false,"input":["text"],"cost":{"input":0,"output":0,"cacheRead":0,"cacheWrite":0},"contextWindow":32000,"maxTokens":4096}],"map":{"ci-hub/auto":{}}}'
  fi

  # Extract the two JSON fragments we need to embed in the config
  MODELS_ARRAY=$(echo "${MODELS_JSON}" | node -e "process.stdin.on('data',d=>{const o=JSON.parse(d);console.log(JSON.stringify(o.models,null,10))})" 2>/dev/null || echo '[]')
  MODELS_MAP=$(echo "${MODELS_JSON}" | node -e "process.stdin.on('data',d=>{const o=JSON.parse(d);console.log(JSON.stringify(o.map,null,8))})" 2>/dev/null || echo '{}')

  echo "CI Hub: discovered $(echo "${MODELS_ARRAY}" | grep -c '"id"') model(s) from inference endpoint"

  # Keep the gateway loopback-only. The published app URL points at the
  # setup/proxy UI on port 18789, which forwards internally to 127.0.0.1:18790.
  # That keeps Hub "Open" links working at http://<device-ip>:30189 on the LAN
  # without exposing the raw gateway listener directly.
  # Write openclaw.json
  cat > "${CONFIG_FILE}" <<OCEOF
{
  "wizard": {
    "lastRunAt": "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)",
    "lastRunVersion": "auto-configured",
    "lastRunCommand": "hub-auto-config",
    "lastRunMode": "local"
  },
  "models": {
    "mode": "merge",
    "providers": {
      "ci-hub": {
        "baseUrl": "${INFERENCE_URL}",
        "apiKey": "ollama",
        "api": "openai-completions",
        "models": ${MODELS_ARRAY}
      }
    }
  },
  "agents": {
    "defaults": {
      "model": { "primary": "ci-hub/auto" },
      "models": ${MODELS_MAP},
      "workspace": "${STATE_DIR}/workspace"
    }
  },
  "tools": { "profile": "coding" },
  "commands": { "native": "auto", "nativeSkills": "auto", "restart": true, "ownerDisplay": "raw" },
  "session": { "dmScope": "per-channel-peer" },
  "gateway": {
    "port": 18790,
    "mode": "local",
    "bind": "loopback",
    "auth": { "mode": "token", "token": "${GATEWAY_TOKEN}" },
    "controlUi": { "allowInsecureAuth": true, "dangerouslyDisableDeviceAuth": true },
    "tailscale": { "mode": "off", "resetOnExit": false }
  },
  "update": { "checkOnStart": false },
  "meta": {
    "lastTouchedVersion": "auto-configured",
    "lastTouchedAt": "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)"
  }
}
OCEOF

  # Write .env with gateway token
  cat > "${ENV_FILE}" <<ENVEOF
# OpenClaw Configuration
# Auto-configured by CI Hub
OPENCLAW_GATEWAY_TOKEN=${GATEWAY_TOKEN}
ENVEOF

  chmod 600 "${CONFIG_FILE}" "${ENV_FILE}"

  echo "CI Hub: OpenClaw auto-configuration complete"
fi

# ── Hand off to the upstream setup-server ───────────────────────────────
exec docker-entrypoint.sh node /app/setup-server.cjs
