#!/bin/sh
# CI Hub OpenClaw entrypoint — auto-configures the gateway to use
# Hub-managed inference so the onboarding wizard is skipped entirely.
#
# Distributed via two paths:
#   1. Marketplace app listing — preferred path; copied into /data volume
#      by the Hub install pipeline (copyDataDir).
#   2. Backend bundle fallback — bundled with packages/backend via build.ts
#      and written by install-app-command.ts when the app payload is missing
#      the file (e.g. copyDataDir was skipped because app-data already exists).
#
# Environment variables consumed:
#   OLLAMA_HOST                — Ollama container URL (injected by Hub); its /v1 is OpenAI-compatible
#   HUB_URL                    — Hub base URL (optional; defaults to http://ci-os-hub:3000)
#   OPENCLAW_DATA_DIR          — state directory (default: /data/.openclaw)
#   OPENCLAW_GATEWAY_TOKEN     — gateway auth token (auto-generated by Hub form field)
#   CLAWDBOT_GATEWAY_TOKEN     — legacy gateway token env var (fallback)
#
# If openclaw.json already exists (user has configured OpenClaw), this
# script is a no-op and falls through to the upstream setup-server.

set -e

STATE_DIR="${OPENCLAW_DATA_DIR:-${OPENCLAW_STATE_DIR:-/data/.openclaw}}"
CONFIG_FILE="${STATE_DIR}/openclaw.json"
ENV_FILE="${STATE_DIR}/.env"

# Apps talk to the Ollama container directly (its OpenAI-compatible /v1) — the Hub
# no longer proxies inference. OLLAMA_HOST is injected by the Hub for every app.
INFERENCE_URL="${OLLAMA_HOST:-http://ci-hub-ollama:11434}"
INFERENCE_URL="${INFERENCE_URL%/}/v1"
HUB_BASE_URL="${HUB_URL:-http://ci-os-hub:3000}"
HUB_CREDENTIALS_URL="${HUB_BASE_URL%/}/api/inference/apps/openclaw/credentials"

# ── Auto-configure on first run, or migrate legacy ci-hub/auto configs ─
NEEDS_CONFIG_REWRITE=0
if [ ! -f "${CONFIG_FILE}" ]; then
  NEEDS_CONFIG_REWRITE=1
elif grep -q '"ci-hub/auto"' "${CONFIG_FILE}" 2>/dev/null; then
  NEEDS_CONFIG_REWRITE=1
fi

if [ -n "${OLLAMA_HOST}" ] && [ "${NEEDS_CONFIG_REWRITE}" -eq 1 ]; then
  echo "CI Hub: configuring OpenClaw with direct inference endpoint ${INFERENCE_URL}"

  # Ensure directories
  mkdir -p "${STATE_DIR}/workspace" "${STATE_DIR}/agents/main/sessions"

  # Use the Hub-generated gateway token (from form field), or generate one
  GATEWAY_TOKEN="${OPENCLAW_GATEWAY_TOKEN:-${CLAWDBOT_GATEWAY_TOKEN:-$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')}}"

  # ── Discover models from Ollama and the Hub credentials endpoint ────────
  # Build the model list from Ollama's /v1/models (native model ids), then
  # ask the Hub which local model it prefers for OpenClaw. This avoids the
  # synthetic "ci-hub/auto" placeholder that OpenClaw cannot actually send to
  # Ollama.
  MODELS_JSON=""
  MODELS_MAP="{}"
  if command -v node >/dev/null 2>&1; then
    MODELS_JSON=$(node -e "
      const inferenceUrl = '${INFERENCE_URL}';
      const credentialsUrl = '${HUB_CREDENTIALS_URL}';
      const baseEntry = (id, meta = {}) => ({
        id,
        name: id,
        reasoning: false,
        input: ['text'],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: meta.context_window || 32000,
        maxTokens: meta.max_tokens || 4096,
      });
      (async () => {
        let preferredModelId = '';
        try {
          const credentialsResponse = await fetch(credentialsUrl);
          if (credentialsResponse.ok) {
            const credentials = await credentialsResponse.json();
            if (credentials?.provider === 'ollama' && typeof credentials?.chatModelId === 'string') {
              preferredModelId = credentials.chatModelId;
            }
          }
        } catch {}

        let discovered = [];
        try {
          const modelsResponse = await fetch(inferenceUrl + '/models');
          if (modelsResponse.ok) {
            const payload = await modelsResponse.json();
            discovered = Array.isArray(payload?.data) ? payload.data : [];
          }
        } catch {}

        const models = [];
        const seen = new Set();
        const addModel = (id, meta = {}) => {
          if (typeof id !== 'string' || id.length === 0 || seen.has(id)) return;
          seen.add(id);
          models.push(baseEntry(id, meta));
        };

        discovered.forEach((model) => addModel(model?.id, model));
        addModel(preferredModelId);

        const primary = models.find((model) => model.id === preferredModelId)?.id || models[0]?.id || null;
        const map = {};
        models.forEach((model) => { map['ci-hub/' + model.id] = {}; });
        console.log(JSON.stringify({ models, map, primary }));
      })().catch(() => {
        console.log(JSON.stringify({ models: [], map: {}, primary: null }));
      });
    " 2>/dev/null) || true
  fi

  # Fallback if node fetch failed
  if [ -z "${MODELS_JSON}" ]; then
    MODELS_JSON='{"models":[],"map":{},"primary":null}'
  fi

  # Extract the JSON fragments we need to embed in the config
  MODELS_ARRAY=$(echo "${MODELS_JSON}" | node -e "process.stdin.on('data',d=>{const o=JSON.parse(d);console.log(JSON.stringify(o.models,null,10))})" 2>/dev/null || echo '[]')
  MODELS_MAP=$(echo "${MODELS_JSON}" | node -e "process.stdin.on('data',d=>{const o=JSON.parse(d);console.log(JSON.stringify(o.map,null,8))})" 2>/dev/null || echo '{}')
  PRIMARY_MODEL=$(echo "${MODELS_JSON}" | node -e "process.stdin.on('data',d=>{const o=JSON.parse(d);process.stdout.write(typeof o.primary==='string'?o.primary:'')})" 2>/dev/null || echo '')

  if [ -n "${PRIMARY_MODEL}" ]; then
    PRIMARY_MODEL_JSON="\"ci-hub/${PRIMARY_MODEL}\""
  else
    PRIMARY_MODEL_JSON="null"
  fi

  echo "CI Hub: discovered $(echo "${MODELS_ARRAY}" | grep -c '"id"') model(s) from inference endpoint"

  # Keep the gateway loopback-only. The published app URL points at the
  # setup/proxy UI on port 18789, which forwards internally to 127.0.0.1:18790.
  # That keeps Hub "Open" links working at http://<device-ip>:30189 on the LAN
  # without exposing the raw gateway listener directly.
  # Write openclaw.json
  cat > "${CONFIG_FILE}" <<OCEOF
{
  "wizard": {
    "lastRunAt": "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)",
    "lastRunVersion": "auto-configured",
    "lastRunCommand": "hub-auto-config",
    "lastRunMode": "local"
  },
  "models": {
    "mode": "merge",
    "providers": {
      "ci-hub": {
        "baseUrl": "${INFERENCE_URL}",
        "apiKey": "ollama",
        "api": "openai-completions",
        "models": ${MODELS_ARRAY}
      }
    }
  },
  "agents": {
    "defaults": {
      "model": { "primary": ${PRIMARY_MODEL_JSON} },
      "models": ${MODELS_MAP},
      "workspace": "${STATE_DIR}/workspace"
    }
  },
  "tools": { "profile": "coding" },
  "commands": { "native": "auto", "nativeSkills": "auto", "restart": true, "ownerDisplay": "raw" },
  "session": { "dmScope": "per-channel-peer" },
  "gateway": {
    "port": 18790,
    "mode": "local",
    "bind": "loopback",
    "auth": { "mode": "token", "token": "${GATEWAY_TOKEN}" },
    "controlUi": { "allowInsecureAuth": true, "dangerouslyDisableDeviceAuth": true },
    "tailscale": { "mode": "off", "resetOnExit": false }
  },
  "update": { "checkOnStart": false },
  "meta": {
    "lastTouchedVersion": "auto-configured",
    "lastTouchedAt": "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)"
  }
}
OCEOF

  # Write .env with gateway token
  cat > "${ENV_FILE}" <<ENVEOF
# OpenClaw Configuration
# Auto-configured by CI Hub
OPENCLAW_GATEWAY_TOKEN=${GATEWAY_TOKEN}
ENVEOF

  chmod 600 "${CONFIG_FILE}" "${ENV_FILE}"

  echo "CI Hub: OpenClaw auto-configuration complete"
fi

# ── Hand off to the upstream setup-server ───────────────────────────────
exec docker-entrypoint.sh node /app/setup-server.cjs
