#!/bin/sh
# CI Hub OpenClaw entrypoint — auto-configures the gateway to use Hub-managed
# inference and keeps the Ollama model catalog in sync on every container start.
#
# Calls the Hub's per-app bootstrap endpoint on every container start:
#   GET ${HUB_BASE_URL}/api/inference/apps/openclaw/bootstrap.env
#
# Bootstrap delegates "which model is best for the detected hardware" to the
# Hub's AppBootstrapService. We merge that into .env, sync the local Ollama
# catalog into openclaw.json on every start, and write structural defaults on
# first install.
#
# Environment variables consumed:
#   OLLAMA_HOST                — native Ollama URL (injected by Hub, e.g. http://host.docker.internal:11434)
#   OPENAI_API_BASE            — OpenAI-compatible /v1 URL (from bootstrap.env or app.env)
#   HUB_INFERENCE_URL          — legacy Hub-proxied inference URL (optional)
#   HUB_URL                    — Hub base URL fallback (default: http://ci-os-hub:5002)
#   OPENCLAW_DATA_DIR          — state directory (default: /data/.openclaw)
#   OPENCLAW_GATEWAY_TOKEN     — gateway auth token (auto-generated by Hub form field)
#   CLAWDBOT_GATEWAY_TOKEN     — legacy gateway token env var (fallback)
#   APP_PUBLIC_URL / APP_URL   — Hub-published URLs for Control UI origin allowlist
#
# Bundled with the marketplace app listing and copied into the container's
# /data volume by the Hub install pipeline (copyDataDir).

set -e

STATE_DIR="${OPENCLAW_DATA_DIR:-${OPENCLAW_STATE_DIR:-/data/.openclaw}}"
CONFIG_FILE="${STATE_DIR}/openclaw.json"
ENV_FILE="${STATE_DIR}/.env"

# Derive the bootstrap endpoint from HUB_INFERENCE_URL by stripping the
# /api/inference/v1 suffix. Resilient to missing trailing slash.
hub_base_url() {
  case "${HUB_INFERENCE_URL:-}" in
    "") echo "" ;;
    */api/inference/v1) echo "${HUB_INFERENCE_URL%/api/inference/v1}" ;;
    */api/inference/v1/) echo "${HUB_INFERENCE_URL%/api/inference/v1/}" ;;
    *) echo "${HUB_INFERENCE_URL}" ;;
  esac
}

HUB_BASE_URL="$(hub_base_url)"
if [ -z "${HUB_BASE_URL}" ]; then
  HUB_BASE_URL="${HUB_URL:-http://ci-os-hub:5002}"
fi

# Fallback list used when the Hub doesn't send X-Hub-Managed-Keys
# (older Hub releases). Kept in sync with AppBootstrapService's
# OPENCLAW env keys as a last resort.
FALLBACK_MANAGED_KEYS="OPENAI_API_BASE,OPENAI_API_KEY,DEFAULT_MODEL,DEFAULT_MODEL_BACKEND_ID,EMBEDDINGS_MODEL,EMBEDDINGS_MODEL_BACKEND_ID,OLLAMA_HOST,CI_LLM_NUM_CTX"

# Convert a comma-separated key list into a ^KEY= alternation pattern.
keys_to_pattern() {
  csv="$1"
  if [ -z "${csv}" ]; then
    echo ""
    return 0
  fi
  printf '%s' "${csv}" | tr ',' '\n' | awk 'NF { printf("%s^%s=", sep, $0); sep="|" }'
}

resolve_ollama_native_url() {
  if [ -n "${OLLAMA_HOST:-}" ]; then
    printf '%s' "${OLLAMA_HOST%/}"
    return 0
  fi

  if [ -f "${ENV_FILE}" ]; then
    line="$(grep -E '^OLLAMA_HOST=' "${ENV_FILE}" 2>/dev/null | tail -n1 | cut -d= -f2- | tr -d '"' || true)"
    if [ -n "${line}" ]; then
      printf '%s' "${line%/}"
      return 0
    fi
  fi

  if [ -n "${OPENAI_API_BASE:-}" ]; then
    case "${OPENAI_API_BASE}" in
      */v1) printf '%s' "${OPENAI_API_BASE%/v1}"; return 0 ;;
    esac
  fi

  if [ -f "${ENV_FILE}" ]; then
    line="$(grep -E '^OPENAI_API_BASE=' "${ENV_FILE}" 2>/dev/null | tail -n1 | cut -d= -f2- | tr -d '"' || true)"
    case "${line}" in
      */v1) printf '%s' "${line%/v1}"; return 0 ;;
    esac
  fi

  printf '%s' "http://host.docker.internal:11434"
}

resolve_inference_api_key() {
  if [ -n "${OPENAI_API_KEY:-}" ]; then
    printf '%s' "${OPENAI_API_KEY}"
    return 0
  fi

  if [ -f "${ENV_FILE}" ]; then
    line="$(grep -E '^OPENAI_API_KEY=' "${ENV_FILE}" 2>/dev/null | tail -n1 | cut -d= -f2- | tr -d '"' || true)"
    if [ -n "${line}" ]; then
      printf '%s' "${line}"
      return 0
    fi
  fi

  printf '%s' "ollama"
}

# ── Pull bootstrap.env from the Hub and merge it into .env ──────────────
if [ -n "${HUB_BASE_URL}" ]; then
  BOOTSTRAP_URL="${HUB_BASE_URL}/api/inference/apps/openclaw/bootstrap.env"
  echo "CI Hub: fetching ${BOOTSTRAP_URL}"
  mkdir -p "${STATE_DIR}/workspace" "${STATE_DIR}/agents/main/sessions"

  HEADERS_TMP="$(mktemp)"
  if BODY="$(curl --silent --show-error --fail --max-time 5 --retry 1 --retry-delay 2 -D "${HEADERS_TMP}" "${BOOTSTRAP_URL}" 2>/dev/null)"; then
    MANAGED_KEYS="$(awk -F': ' 'tolower($1) == "x-hub-managed-keys" { sub(/\r$/, "", $2); print $2; exit }' "${HEADERS_TMP}")"
    if [ -z "${MANAGED_KEYS}" ]; then
      echo "CI Hub: X-Hub-Managed-Keys header missing; falling back to hardcoded list"
      MANAGED_KEYS="${FALLBACK_MANAGED_KEYS}"
    fi
    PATTERN="$(keys_to_pattern "${MANAGED_KEYS}")"
    HUB_LINES="$(printf '%s\n' "${BODY}" | grep -E "${PATTERN}" || true)"

    if [ -n "${HUB_LINES}" ]; then
      EXISTING=""
      if [ -f "${ENV_FILE}" ]; then
        EXISTING="$(grep -Ev "${PATTERN}" "${ENV_FILE}" || true)"
      fi
      TMP="$(mktemp)"
      {
        if [ -n "${EXISTING}" ]; then
          printf '%s\n' "${EXISTING}"
        else
          printf '# OpenClaw Configuration\n# Hub-managed keys are rewritten on every container start.\n\n'
        fi
        printf '%s\n' "${HUB_LINES}"
      } > "${TMP}"
      mv "${TMP}" "${ENV_FILE}"
      chmod 600 "${ENV_FILE}" 2>/dev/null || true
      echo "CI Hub: merged Hub-managed keys into ${ENV_FILE}"
    else
      echo "CI Hub: Hub response did not contain any managed keys; ${ENV_FILE} left alone"
    fi
  else
    echo "CI Hub: Hub bootstrap endpoint unreachable; falling back to OLLAMA_HOST env"
  fi
  rm -f "${HEADERS_TMP}"
fi

# ── First install: write structural openclaw.json if missing ────────────
# openclaw.json contains the gateway/auth/UI config that lets OpenClaw run.
# The ci-hub provider points at native Ollama; per-model selection is synced
# from the host on every container start.
if [ ! -f "${CONFIG_FILE}" ]; then
  echo "CI Hub: writing first-run openclaw.json"
  GATEWAY_TOKEN="${OPENCLAW_GATEWAY_TOKEN:-${CLAWDBOT_GATEWAY_TOKEN:-$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')}}"
  NOW="$(date -u +%Y-%m-%dT%H:%M:%S.000Z)"
  OLLAMA_NATIVE_URL="$(resolve_ollama_native_url)"
  INFERENCE_API_KEY="$(resolve_inference_api_key)"

  # Keep the gateway loopback-only. The published app URL points at the
  # setup/proxy UI on port 18789, which forwards internally to 127.0.0.1:18790.
  # That keeps Hub "Open" links working at http://<device-ip>:30189 on the LAN
  # without exposing the raw gateway listener directly.

  cat > "${CONFIG_FILE}" <<OCEOF
{
  "wizard": {
    "lastRunAt": "${NOW}",
    "lastRunVersion": "auto-configured",
    "lastRunCommand": "hub-auto-config",
    "lastRunMode": "local"
  },
  "models": {
    "mode": "merge",
    "providers": {
      "ci-hub": {
        "baseUrl": "${OLLAMA_NATIVE_URL}",
        "apiKey": "${INFERENCE_API_KEY}",
        "api": "ollama",
        "models": []
      }
    }
  },
  "agents": {
    "defaults": {
      "model": { "primary": null },
      "models": {},
      "workspace": "${STATE_DIR}/workspace"
    }
  },
  "tools": { "profile": "minimal" },
  "commands": { "native": "auto", "nativeSkills": "auto", "restart": true, "ownerDisplay": "raw" },
  "session": { "dmScope": "per-channel-peer" },
  "gateway": {
    "port": 18790,
    "mode": "local",
    "bind": "loopback",
    "auth": { "mode": "token", "token": "${GATEWAY_TOKEN}" },
    "controlUi": {
      "allowInsecureAuth": true,
      "dangerouslyDisableDeviceAuth": true,
      "dangerouslyAllowHostHeaderOriginFallback": true
    },
    "tailscale": { "mode": "off", "resetOnExit": false }
  },
  "update": { "checkOnStart": false },
  "meta": {
    "lastTouchedVersion": "auto-configured",
    "lastTouchedAt": "${NOW}"
  }
}
OCEOF

  # Append the gateway token alongside the Hub-merged .env. We don't put it
  # through the merge step because OPENCLAW_GATEWAY_TOKEN is not a Hub-managed
  # key — it's per-install and we never want to overwrite it.
  if ! grep -qE '^OPENCLAW_GATEWAY_TOKEN=' "${ENV_FILE}" 2>/dev/null; then
    echo "OPENCLAW_GATEWAY_TOKEN=${GATEWAY_TOKEN}" >> "${ENV_FILE}"
  fi
  chmod 600 "${CONFIG_FILE}" "${ENV_FILE}" 2>/dev/null || true
  echo "CI Hub: first-run openclaw.json + gateway token written"
fi

# ── Every start: sync Ollama models into openclaw.json ──────────────────
sync_ollama_models() {
  if [ ! -f "${CONFIG_FILE}" ]; then
    return 0
  fi
  if ! command -v node >/dev/null 2>&1; then
    echo "CI Hub: node not available; skipping Ollama model sync"
    return 0
  fi

  OLLAMA_NATIVE_URL="$(resolve_ollama_native_url)"
  INFERENCE_API_KEY="$(resolve_inference_api_key)"

  CONFIG_FILE="${CONFIG_FILE}" \
  ENV_FILE="${ENV_FILE}" \
  OLLAMA_NATIVE_URL="${OLLAMA_NATIVE_URL}" \
  INFERENCE_API_KEY="${INFERENCE_API_KEY}" \
    node - <<'NODE'
const fs = require('fs');

const configPath = process.env.CONFIG_FILE;
const envPath = process.env.ENV_FILE;
const ollamaNativeUrl = (process.env.OLLAMA_NATIVE_URL || '').replace(/\/$/, '');
const inferenceApiKey = process.env.INFERENCE_API_KEY || 'ollama';

const readEnvValue = (key) => {
  try {
    const body = fs.readFileSync(envPath, 'utf8');
    for (const line of body.split('\n')) {
      if (line.startsWith(key + '=')) {
        return line.slice(key.length + 1).trim().replace(/^"|"$/g, '');
      }
    }
  } catch {}
  return '';
};

const defaultModel = readEnvValue('DEFAULT_MODEL');
const isEmbeddingModel = (id) => /embed/i.test(id);

// Hardware-aware context window injected by the Hub (CI_LLM_NUM_CTX). Caps both
// the agent's token budget and the native Ollama num_ctx so OpenClaw doesn't
// pack to Ollama's oversized memory-based default (e.g. 262144 on APUs).
const hubNumCtxRaw = readEnvValue('CI_LLM_NUM_CTX') || process.env.CI_LLM_NUM_CTX || '';
const hubNumCtx = Number.parseInt(hubNumCtxRaw, 10);
const numCtx = Number.isFinite(hubNumCtx) && hubNumCtx > 0 ? hubNumCtx : undefined;

const fetchJson = async (url, init) => {
  const response = await fetch(url, init);
  if (!response.ok) return null;
  return response.json();
};

const modelCapabilities = async (id) => {
  const payload = await fetchJson(ollamaNativeUrl + '/api/show', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: id }),
  });
  const caps = Array.isArray(payload?.capabilities) ? payload.capabilities : [];
  // model_info exposes the model's trained context as "<arch>.context_length".
  const info = payload?.model_info && typeof payload.model_info === 'object' ? payload.model_info : {};
  const ctxEntry = Object.entries(info).find(([k]) => k.endsWith('.context_length'));
  // model_info may serialize the value as a number or a numeric string — coerce.
  const ctxNum = ctxEntry ? Number(ctxEntry[1]) : Number.NaN;
  const contextLimit = Number.isFinite(ctxNum) && ctxNum > 0 ? ctxNum : undefined;
  return {
    supportsTools: caps.includes('tools'),
    reasoning: caps.includes('thinking'),
    vision: caps.includes('vision'),
    contextLimit,
  };
};

const baseEntry = (id, name, caps) => {
  // Never request more context than the model supports: numCtx is computed for
  // the Hub's default chat model and may exceed a smaller model's window. When
  // the per-model limit is unknown, stay conservative at the historical 32000
  // default rather than the possibly-larger numCtx.
  const effCtx = numCtx ? Math.min(numCtx, caps?.contextLimit ?? 32000) : undefined;
  // Without an explicit num_ctx, advertise the historical 32000 default but never
  // more than the model's known window (small-window models would be rejected).
  const contextWindow = effCtx ?? Math.min(32000, caps?.contextLimit ?? 32000);
  const entry = {
    id,
    name: name || id,
    reasoning: caps?.reasoning === true,
    input: caps?.vision ? ['text', 'image'] : ['text'],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow,
    // Output budget can't exceed the total context window.
    maxTokens: Math.min(4096, contextWindow),
    compat: { supportsTools: caps?.supportsTools === true },
  };
  if (effCtx) entry.options = { num_ctx: effCtx };
  return entry;
};

(async () => {
  let discovered = [];
  const tagsPayload = await fetchJson(ollamaNativeUrl + '/api/tags');
  if (Array.isArray(tagsPayload?.models)) {
    discovered = tagsPayload.models.map((model) => ({ id: model.name }));
  }

  const discoveredIds = new Set(
    discovered.map((model) => model?.id).filter((id) => typeof id === 'string' && id.length > 0),
  );

  const models = [];
  const seen = new Set();
  const addModel = async (id, name) => {
    if (typeof id !== 'string' || id.length === 0 || seen.has(id) || isEmbeddingModel(id)) return false;
    if (!discoveredIds.has(id)) return false;
    seen.add(id);
    const caps = await modelCapabilities(id);
    models.push(baseEntry(id, name || id, caps));
    return true;
  };

  for (const model of discovered) {
    await addModel(model?.id, model?.id);
  }

  const defaultModelAvailable = defaultModel && discoveredIds.has(defaultModel) ? defaultModel : null;
  const firstModelId = models.find((model) => model.id !== 'auto')?.id ?? null;
  const autoTargetId = defaultModelAvailable || firstModelId;

  if (autoTargetId) {
    const autoCaps = await modelCapabilities(autoTargetId);
    models.unshift(baseEntry('auto', 'Hub Auto (' + autoTargetId + ')', autoCaps));
  }

  const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  config.models = config.models || { mode: 'merge', providers: {} };
  config.models.mode = 'merge';
  config.models.providers = config.models.providers || {};
  config.models.providers['ci-hub'] = {
    baseUrl: ollamaNativeUrl,
    apiKey: inferenceApiKey,
    api: 'ollama',
    models,
  };

  const existingModels = config.agents?.defaults?.models ?? {};
  const map = Object.fromEntries(
    Object.entries(existingModels).filter(([key]) => !key.startsWith('ci-hub/')),
  );
  for (const model of models) {
    const key = 'ci-hub/' + model.id;
    map[key] = existingModels[key] ?? {};
  }

  config.agents = config.agents || { defaults: {} };
  config.agents.defaults = config.agents.defaults || {};
  config.agents.defaults.models = map;

  const availableIds = new Set(models.map((model) => model.id));
  const existingPrimary = config.agents.defaults.model?.primary;
  let primaryId = null;
  if (typeof existingPrimary === 'string' && existingPrimary.startsWith('ci-hub/')) {
    const existingId = existingPrimary.slice('ci-hub/'.length);
    if (availableIds.has(existingId)) {
      primaryId = existingId;
    }
  }
  if (!primaryId) {
    primaryId = defaultModelAvailable || firstModelId;
  }
  if (primaryId) {
    config.agents.defaults.model = { primary: 'ci-hub/' + primaryId };
  } else {
    config.agents.defaults.model = { primary: null };
  }

  const hasToolCapableModel = models.some((model) => model.compat?.supportsTools === true);
  config.tools = config.tools || {};
  config.tools.profile = hasToolCapableModel ? 'coding' : 'minimal';

  if (models.length === 0) {
    console.warn('CI Hub: no local Ollama chat models found at ' + ollamaNativeUrl + '; left existing agent defaults intact');
    return;
  }

  fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');
  console.log('CI Hub: synced ' + models.length + ' Ollama model(s) via native API at ' + ollamaNativeUrl);
})().catch((error) => {
  console.error('CI Hub: Ollama model sync failed: ' + (error instanceof Error ? error.message : String(error)));
});
NODE
}

sync_ollama_models

# ── Every start: allow Control UI from Hub-published URLs ───────────────
patch_control_ui_origins() {
  if [ ! -f "${CONFIG_FILE}" ]; then
    return 0
  fi
  if ! command -v node >/dev/null 2>&1; then
    echo "CI Hub: node not available; skipping Control UI origin patch"
    return 0
  fi

  CONFIG_FILE="${CONFIG_FILE}" \
  APP_PUBLIC_URL="${APP_PUBLIC_URL:-}" \
  APP_URL="${APP_URL:-}" \
  APP_PORT="${APP_PORT:-}" \
  APP_LOCAL_DOMAIN="${APP_LOCAL_DOMAIN:-}" \
  INTERNAL_IP="${INTERNAL_IP:-}" \
    node - <<'NODE'
const fs = require('fs');

const configPath = process.env.CONFIG_FILE;
const origins = new Set([
  'http://127.0.0.1:18789',
  'http://localhost:18789',
]);

const addOrigin = (value) => {
  if (typeof value !== 'string' || value.trim().length === 0) return;
  try {
    origins.add(new URL(value).origin);
  } catch {}
};

addOrigin(process.env.APP_PUBLIC_URL);
addOrigin(process.env.APP_URL);

const port = process.env.APP_PORT;
if (port) {
  origins.add('http://127.0.0.1:' + port);
  origins.add('http://localhost:' + port);
  const ip = process.env.INTERNAL_IP;
  if (ip && ip !== '0.0.0.0' && ip !== '::') {
    origins.add('http://' + ip + ':' + port);
  }
}

const localDomain = process.env.APP_LOCAL_DOMAIN;
if (localDomain) {
  addOrigin('http://' + localDomain);
  addOrigin('https://' + localDomain);
}

const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
config.gateway = config.gateway || {};
config.gateway.controlUi = config.gateway.controlUi || {};
config.gateway.controlUi.allowInsecureAuth = true;
config.gateway.controlUi.dangerouslyDisableDeviceAuth = true;
config.gateway.controlUi.dangerouslyAllowHostHeaderOriginFallback = true;
config.gateway.controlUi.allowedOrigins = [...origins].sort();
fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');
NODE
}

patch_control_ui_origins

# ── Hand off to the upstream setup-server ───────────────────────────────
exec docker-entrypoint.sh node /app/setup-server.cjs
