// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type UserContextDto = {
    [key: string]: unknown;
};

export type AppContextDto = {
    [key: string]: unknown;
};

export type UserSettingsBody = {
    [key: string]: unknown;
};

export type AcknowledgeWelcomeBody = {
    [key: string]: unknown;
};

export type MyAppsDto = {
    [key: string]: unknown;
};

export type InstallQueueDto = {
    [key: string]: unknown;
};

export type GuestAppsDto = {
    [key: string]: unknown;
};

export type GetRandomPortDto = {
    [key: string]: unknown;
};

export type AppRuntimeMonitorDto = {
    [key: string]: unknown;
};

export type GetAppDto = {
    [key: string]: unknown;
};

export type GetComposeDiffDto = {
    [key: string]: unknown;
};

export type GetConfigDiffDto = {
    [key: string]: unknown;
};

export type AppRuntimeHealthDto = {
    [key: string]: unknown;
};

export type UpdateInferencePreferencesBody = {
    [key: string]: unknown;
};

export type UpdateRocmInstallStateBody = {
    [key: string]: unknown;
};

export type LoadDto = {
    [key: string]: unknown;
};

export type SystemResourcesDto = {
    [key: string]: unknown;
};

export type FactoryResetDto = {
    [key: string]: unknown;
};

export type SearchAppsDto = {
    [key: string]: unknown;
};

export type PullDto = {
    [key: string]: unknown;
};

export type CreateAppStoreBodyDto = {
    [key: string]: unknown;
};

export type AppStoreDto = {
    [key: string]: unknown;
};

export type AllAppStoresDto = {
    [key: string]: unknown;
};

export type UpdateAppStoreBodyDto = {
    [key: string]: unknown;
};

export type UpdateAppStoreDto = {
    [key: string]: unknown;
};

export type LoginBody = {
    [key: string]: unknown;
};

export type LoginDto = {
    [key: string]: unknown;
};

export type VerifyTotpBody = {
    [key: string]: unknown;
};

export type RegisterBody = {
    [key: string]: unknown;
};

export type RegisterDto = {
    [key: string]: unknown;
};

export type SessionRefreshDto = {
    [key: string]: unknown;
};

export type PortalSessionHintDto = {
    [key: string]: unknown;
};

export type PortalDesktopExchangeDto = {
    [key: string]: unknown;
};

export type ChangeUsernameBody = {
    [key: string]: unknown;
};

export type ChangePasswordBody = {
    [key: string]: unknown;
};

export type GetTotpUriBody = {
    [key: string]: unknown;
};

export type GetTotpUriDto = {
    [key: string]: unknown;
};

export type SetupTotpBody = {
    [key: string]: unknown;
};

export type DisableTotpBody = {
    [key: string]: unknown;
};

export type ResetPasswordBody = {
    [key: string]: unknown;
};

export type ResetPasswordDto = {
    [key: string]: unknown;
};

export type CheckResetPasswordRequestDto = {
    [key: string]: unknown;
};

export type PasswordResetRequestBody = {
    [key: string]: unknown;
};

export type PasswordResetRequestDto = {
    [key: string]: unknown;
};

export type PasswordResetVerifyResponseDto = {
    [key: string]: unknown;
};

export type PasswordResetCompleteBody = {
    [key: string]: unknown;
};

export type PasswordResetCompleteDto = {
    [key: string]: unknown;
};

export type AppFormBody = {
    [key: string]: unknown;
};

export type LifecycleRequestDto = {
    [key: string]: unknown;
};

export type UninstallAppBody = {
    [key: string]: unknown;
};

export type UpdateAppBody = {
    [key: string]: unknown;
};

export type CancelOperationBody = {
    [key: string]: unknown;
};

export type CancelOperationResponseDto = {
    [key: string]: unknown;
};

export type BackupRequestDto = {
    [key: string]: unknown;
};

export type RestoreAppBackupDto = {
    [key: string]: unknown;
};

export type GetAppBackupsDto = {
    [key: string]: unknown;
};

export type DeleteAppBackupBodyDto = {
    [key: string]: unknown;
};

export type LinksDto = {
    [key: string]: unknown;
};

export type LinkBodyDto = {
    [key: string]: unknown;
};

export type EditLinkBodyDto = {
    [key: string]: unknown;
};

export type GetUserConfigDto = {
    [key: string]: unknown;
};

export type UpdateUserConfigDto = {
    [key: string]: unknown;
};

export type CreateCustomAppDto = {
    [key: string]: unknown;
};

export type CreateCustomAppResponseDto = {
    [key: string]: unknown;
};

export type UpdateCustomAppDto = {
    [key: string]: unknown;
};

export type UpdateAppMetadataDto = {
    [key: string]: unknown;
};

export type UserContextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user-context';
};

export type UserContextResponses = {
    default: UserContextDto;
};

export type UserContextResponse = UserContextResponses[keyof UserContextResponses];

export type GetStoreAlternativesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/store/alternatives';
};

export type GetStoreAlternativesErrors = {
    /**
     * CI Cloud unreachable or CI_CLOUD_URL not set
     */
    503: unknown;
};

export type GetStoreAlternativesResponses = {
    /**
     * Alternatives JSON
     */
    200: unknown;
};

export type GetStoreListingsData = {
    body?: never;
    path?: never;
    query: {
        tags: string;
        sort: string;
        category: string;
        q: string;
    };
    url: '/api/store/listings';
};

export type GetStoreListingsErrors = {
    /**
     * CI Cloud unreachable or CI_CLOUD_URL not set
     */
    503: unknown;
};

export type GetStoreListingsResponses = {
    /**
     * Store apps JSON array
     */
    200: unknown;
};

export type AppContextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-context';
};

export type AppContextResponses = {
    default: AppContextDto;
};

export type AppContextResponse = AppContextResponses[keyof AppContextResponses];

export type UpdateUserSettingsData = {
    body: UserSettingsBody;
    path?: never;
    query?: never;
    url: '/api/user-settings';
};

export type UpdateUserSettingsResponses = {
    200: unknown;
};

export type UpdateAdvancedModeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user-advanced-mode';
};

export type UpdateAdvancedModeResponses = {
    200: unknown;
};

export type AcknowledgeWelcomeData = {
    body: AcknowledgeWelcomeBody;
    path?: never;
    query?: never;
    url: '/api/acknowledge-welcome';
};

export type AcknowledgeWelcomeResponses = {
    200: unknown;
};

export type CompleteOnboardingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/complete-onboarding';
};

export type CompleteOnboardingResponses = {
    200: unknown;
};

export type RestartOnboardingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/restart-onboarding';
};

export type RestartOnboardingResponses = {
    200: unknown;
};

export type ResetRegistrationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/reset';
};

export type ResetRegistrationResponses = {
    /**
     * Registration reset successfully
     */
    200: unknown;
};

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/status';
};

export type GetStatusResponses = {
    /**
     * Returns the explicit provisioning status
     */
    200: unknown;
};

export type GetStateDriftData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/state-drift';
};

export type GetStateDriftResponses = {
    /**
     * Returns drift signals when local and portal state disagree
     */
    200: unknown;
};

export type PrepareFreshSetupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/prepare-fresh';
};

export type PrepareFreshSetupResponses = {
    /**
     * Local registration artifacts cleared
     */
    200: unknown;
};

export type MarkRestoreIntentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/mark-restore-intent';
};

export type MarkRestoreIntentResponses = {
    /**
     * Restore intent recorded
     */
    200: unknown;
};

export type GetDeviceIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/device-id';
};

export type GetDeviceIdResponses = {
    /**
     * Returns the device ID and registration URL
     */
    200: unknown;
};

export type HandleCallbackData = {
    body?: never;
    path?: never;
    query: {
        device_id: string;
        organization_id: string;
        organization_name: string;
        slug: string;
        subdomain: string;
        tunnel_id: string;
        tunnel_token: string;
        api_key: string;
        domain: string;
    };
    url: '/api/registration/callback';
};

export type HandleCallbackErrors = {
    /**
     * Invalid callback data
     */
    400: unknown;
};

export type HandleCallbackResponses = {
    /**
     * Registration completed successfully
     */
    200: unknown;
};

export type HandleCallbackPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/callback';
};

export type HandleCallbackPostErrors = {
    /**
     * Invalid callback data
     */
    400: unknown;
};

export type HandleCallbackPostResponses = {
    /**
     * Registration completed successfully
     */
    200: unknown;
};

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/config';
};

export type GetConfigResponses = {
    /**
     * Returns the CI Cloud configuration
     */
    200: unknown;
};

export type ValidateOrganizationNameData = {
    body?: never;
    path?: never;
    query: {
        name: string;
    };
    url: '/api/registration/validate';
};

export type ValidateOrganizationNameResponses = {
    /**
     * Returns validation result
     */
    200: unknown;
};

export type VerifyPairingCodeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/verify-pairing-code';
};

export type VerifyPairingCodeErrors = {
    /**
     * Invalid or missing pairing code
     */
    400: unknown;
};

export type VerifyPairingCodeResponses = {
    /**
     * Pairing code verified and device identity bound
     */
    200: unknown;
};

export type ProbeDomainData = {
    body?: never;
    path?: never;
    query: {
        url: string;
    };
    url: '/api/registration/probe-domain';
};

export type ProbeDomainResponses = {
    /**
     * Probe result
     */
    200: unknown;
};

export type PairDeviceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/pair';
};

export type PairDeviceErrors = {
    /**
     * Invalid pairing code or pairing failed
     */
    400: unknown;
};

export type PairDeviceResponses = {
    /**
     * Device paired and registered successfully
     */
    200: unknown;
};

export type RegisterDeviceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registration/register';
};

export type RegisterDeviceErrors = {
    /**
     * Invalid request
     */
    400: unknown;
};

export type RegisterDeviceResponses = {
    /**
     * Registration initiated successfully
     */
    200: unknown;
};

export type GetPortalConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portal/config';
};

export type GetPortalConfigResponses = {
    /**
     * Portal configuration
     */
    200: unknown;
};

export type CheckDnsAvailabilityData = {
    body?: never;
    path?: never;
    query: {
        subdomain: string;
        domain: string;
        appUrn: string;
    };
    url: '/api/cloudflare/check-dns-availability';
};

export type CheckDnsAvailabilityResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type CheckDnsAvailabilityResponse = CheckDnsAvailabilityResponses[keyof CheckDnsAvailabilityResponses];

export type GetDomainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cloudflare/domains';
};

export type GetDomainsResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type GetDomainsResponse = GetDomainsResponses[keyof GetDomainsResponses];

export type GetStatus2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cloudflare/status';
};

export type GetStatus2Responses = {
    default: {
        [key: string]: unknown;
    };
};

export type GetStatus2Response = GetStatus2Responses[keyof GetStatus2Responses];

export type CheckUrlAvailabilityData = {
    body?: never;
    path?: never;
    query: {
        url: string;
    };
    url: '/api/cloudflare/check-url-availability';
};

export type CheckUrlAvailabilityResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type CheckUrlAvailabilityResponse = CheckUrlAvailabilityResponses[keyof CheckUrlAvailabilityResponses];

export type SyncMissingDnsRecordsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cloudflare/sync-dns';
};

export type SyncMissingDnsRecordsResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type SyncMissingDnsRecordsResponse = SyncMissingDnsRecordsResponses[keyof SyncMissingDnsRecordsResponses];

export type RemoveOriginRequestFromAllRoutesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cloudflare/remove-origin-request';
};

export type RemoveOriginRequestFromAllRoutesResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type RemoveOriginRequestFromAllRoutesResponse = RemoveOriginRequestFromAllRoutesResponses[keyof RemoveOriginRequestFromAllRoutesResponses];

export type RemoveCatchAllRoutesData = {
    body?: never;
    path?: never;
    query: {
        tunnelId: string;
    };
    url: '/api/cloudflare/remove-catch-all-routes';
};

export type RemoveCatchAllRoutesResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type RemoveCatchAllRoutesResponse = RemoveCatchAllRoutesResponses[keyof RemoveCatchAllRoutesResponses];

export type GetInstalledAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps/installed';
};

export type GetInstalledAppsResponses = {
    default: MyAppsDto;
};

export type GetInstalledAppsResponse = GetInstalledAppsResponses[keyof GetInstalledAppsResponses];

export type GetInstallQueueData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps/install-queue';
};

export type GetInstallQueueResponses = {
    default: InstallQueueDto;
};

export type GetInstallQueueResponse = GetInstallQueueResponses[keyof GetInstallQueueResponses];

export type GetGuestAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps/guest';
};

export type GetGuestAppsResponses = {
    default: GuestAppsDto;
};

export type GetGuestAppsResponse = GetGuestAppsResponses[keyof GetGuestAppsResponses];

export type GetRandomPortData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps/random-port';
};

export type GetRandomPortResponses = {
    default: GetRandomPortDto;
};

export type GetRandomPortResponse = GetRandomPortResponses[keyof GetRandomPortResponses];

export type GetResourceMonitorData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps/resource-monitor';
};

export type GetResourceMonitorResponses = {
    default: AppRuntimeMonitorDto;
};

export type GetResourceMonitorResponse = GetResourceMonitorResponses[keyof GetResourceMonitorResponses];

export type GetAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}';
};

export type GetAppResponses = {
    default: GetAppDto;
};

export type GetAppResponse = GetAppResponses[keyof GetAppResponses];

export type GetAppComposeDiffData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/compose-diff';
};

export type GetAppComposeDiffResponses = {
    default: GetComposeDiffDto;
};

export type GetAppComposeDiffResponse = GetAppComposeDiffResponses[keyof GetAppComposeDiffResponses];

export type GetAppConfigDiffData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/config-diff';
};

export type GetAppConfigDiffResponses = {
    default: GetConfigDiffDto;
};

export type GetAppConfigDiffResponse = GetAppConfigDiffResponses[keyof GetAppConfigDiffResponses];

export type IgnoreAppVersionData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/ignore-version';
};

export type IgnoreAppVersionResponses = {
    200: unknown;
};

export type UnignoreAppVersionData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/unignore-version';
};

export type UnignoreAppVersionResponses = {
    200: unknown;
};

export type CheckAvailabilityData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/check-availability';
};

export type CheckAvailabilityResponses = {
    200: unknown;
};

export type GetRuntimeHealthData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/runtime-health';
};

export type GetRuntimeHealthResponses = {
    default: AppRuntimeHealthDto;
};

export type GetRuntimeHealthResponse = GetRuntimeHealthResponses[keyof GetRuntimeHealthResponses];

export type ResolveAvailabilityData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/apps/{urn}/resolve-availability';
};

export type ResolveAvailabilityResponses = {
    201: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/health';
};

export type HealthResponses = {
    200: unknown;
};

export type GetPreferencesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/preferences';
};

export type GetPreferencesResponses = {
    200: unknown;
};

export type UpdatePreferencesData = {
    body: UpdateInferencePreferencesBody;
    path?: never;
    query?: never;
    url: '/api/inference/preferences';
};

export type UpdatePreferencesResponses = {
    200: unknown;
};

export type GetRuntimeModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/models/runtime';
};

export type GetRuntimeModelsResponses = {
    200: unknown;
};

export type GetStatus3Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/status';
};

export type GetStatus3Responses = {
    200: unknown;
};

export type GetHardwareData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/hardware';
};

export type GetHardwareResponses = {
    200: unknown;
};

export type RescanHardwareData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/hardware/rescan';
};

export type RescanHardwareResponses = {
    201: unknown;
};

export type GetRocmStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/rocm/status';
};

export type GetRocmStatusResponses = {
    200: unknown;
};

export type UpdateRocmInstallStateData = {
    body: UpdateRocmInstallStateBody;
    path?: never;
    query?: never;
    url: '/api/inference/rocm/install-state';
};

export type UpdateRocmInstallStateResponses = {
    201: unknown;
};

export type GetMemoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/memory';
};

export type GetMemoryResponses = {
    200: unknown;
};

export type GetCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/models/catalog';
};

export type GetCatalogResponses = {
    200: unknown;
};

export type GetTrackedModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/models/tracked';
};

export type GetTrackedModelsResponses = {
    200: unknown;
};

export type StartPullModelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/models/pull/start';
};

export type StartPullModelResponses = {
    201: unknown;
};

export type PullModelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/models/pull';
};

export type PullModelResponses = {
    201: unknown;
};

export type LoadModelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/models/load';
};

export type LoadModelResponses = {
    201: unknown;
};

export type UnloadModelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/models/unload';
};

export type UnloadModelResponses = {
    201: unknown;
};

export type PinModelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/models/pin';
};

export type PinModelResponses = {
    201: unknown;
};

export type UnpinModelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/models/unpin';
};

export type UnpinModelResponses = {
    201: unknown;
};

export type GetCloudProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/cloud-providers';
};

export type GetCloudProvidersResponses = {
    200: unknown;
};

export type SetCloudProviderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/cloud-providers';
};

export type SetCloudProviderResponses = {
    201: unknown;
};

export type GetOnboardingProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/onboarding-profile';
};

export type GetOnboardingProfileResponses = {
    200: unknown;
};

export type GetOllamaStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/ollama/status';
};

export type GetOllamaStatusResponses = {
    200: unknown;
};

export type InstallOllamaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inference/ollama/install';
};

export type InstallOllamaResponses = {
    201: unknown;
};

export type GetAppCredentialsData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/inference/apps/{slug}/credentials';
};

export type GetAppCredentialsResponses = {
    200: unknown;
};

export type GetAppCredentialsEnv0Data = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/inference/apps/{slug}/credentials.env';
};

export type GetAppCredentialsEnv0Responses = {
    200: unknown;
};

export type GetAppCredentialsEnv1Data = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/inference/apps/{slug}/bootstrap.env';
};

export type GetAppCredentialsEnv1Responses = {
    200: unknown;
};

export type SystemLoadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/load';
};

export type SystemLoadResponses = {
    default: LoadDto;
};

export type SystemLoadResponse = SystemLoadResponses[keyof SystemLoadResponses];

export type SystemResourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/resources';
};

export type SystemResourcesResponses = {
    default: SystemResourcesDto;
};

export type SystemResourcesResponse = SystemResourcesResponses[keyof SystemResourcesResponses];

export type DownloadHubLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/logs/download';
};

export type DownloadHubLogsResponses = {
    /**
     * Hub logs download
     */
    200: unknown;
};

export type DownloadLocalCertificateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/certificate';
};

export type DownloadLocalCertificateResponses = {
    200: unknown;
};

export type DetectServicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/detect-services';
};

export type DetectServicesResponses = {
    200: unknown;
};

export type GetFullInspectionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system-inspector';
};

export type GetFullInspectionResponses = {
    200: unknown;
};

export type GetContainersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system-inspector/containers';
};

export type GetContainersResponses = {
    200: unknown;
};

export type GetPortsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system-inspector/ports';
};

export type GetPortsResponses = {
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system-inspector/health';
};

export type GetHealthResponses = {
    200: unknown;
};

export type FactoryResetData = {
    body: FactoryResetDto;
    path?: never;
    query?: never;
    url: '/api/system/factory-reset';
};

export type FactoryResetErrors = {
    /**
     * Operator authentication required
     */
    403: unknown;
};

export type FactoryResetResponses = {
    /**
     * Factory reset completed
     */
    200: unknown;
};

export type GetAllAllocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ports';
};

export type GetAllAllocationsResponses = {
    /**
     * Returns all port allocations across all apps
     */
    200: unknown;
};

export type GetAppPortsData = {
    body?: never;
    path: {
        appUrn: string;
    };
    query?: never;
    url: '/api/ports/{appUrn}';
};

export type GetAppPortsResponses = {
    /**
     * Returns port allocations for the specified app
     */
    200: unknown;
};

export type CheckAppPortsData = {
    body?: never;
    path: {
        appUrn: string;
    };
    query?: never;
    url: '/api/ports/{appUrn}/check';
};

export type CheckAppPortsResponses = {
    /**
     * Returns current port status and availability
     */
    200: unknown;
};

export type GetDiagnosticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/network/diagnostics';
};

export type GetDiagnosticsResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type GetDiagnosticsResponse = GetDiagnosticsResponses[keyof GetDiagnosticsResponses];

export type RepairOrphansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/network/repair-orphans';
};

export type RepairOrphansResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type RepairOrphansResponse = RepairOrphansResponses[keyof RepairOrphansResponses];

export type SearchAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/marketplace/apps/search';
};

export type SearchAppsResponses = {
    default: SearchAppsDto;
};

export type SearchAppsResponse = SearchAppsResponses[keyof SearchAppsResponses];

export type GetImageData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/marketplace/apps/{urn}/image';
};

export type GetImageResponses = {
    200: unknown;
};

export type GetAppImageSizeData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/marketplace/apps/{urn}/image-size';
};

export type GetAppImageSizeResponses = {
    200: unknown;
};

export type PullAppStoresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/marketplace/pull';
};

export type PullAppStoresResponses = {
    default: PullDto;
};

export type PullAppStoresResponse = PullAppStoresResponses[keyof PullAppStoresResponses];

export type CreateAppStoreData = {
    body: CreateAppStoreBodyDto;
    path?: never;
    query?: never;
    url: '/api/marketplace/create';
};

export type CreateAppStoreResponses = {
    default: AppStoreDto;
};

export type CreateAppStoreResponse = CreateAppStoreResponses[keyof CreateAppStoreResponses];

export type GetAllAppStoresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/marketplace/all';
};

export type GetAllAppStoresResponses = {
    default: AllAppStoresDto;
};

export type GetAllAppStoresResponse = GetAllAppStoresResponses[keyof GetAllAppStoresResponses];

export type GetEnabledAppStoresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/marketplace/enabled';
};

export type GetEnabledAppStoresResponses = {
    default: AllAppStoresDto;
};

export type GetEnabledAppStoresResponse = GetEnabledAppStoresResponses[keyof GetEnabledAppStoresResponses];

export type DeleteAppStoreData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/marketplace/{id}';
};

export type DeleteAppStoreResponses = {
    200: unknown;
};

export type UpdateAppStoreData = {
    body: UpdateAppStoreBodyDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/marketplace/{id}';
};

export type UpdateAppStoreResponses = {
    default: UpdateAppStoreDto;
};

export type UpdateAppStoreResponse = UpdateAppStoreResponses[keyof UpdateAppStoreResponses];

export type GetTranslationData = {
    body?: never;
    path: {
        ns: string;
        lng: string;
    };
    query?: never;
    url: '/api/i18n/locales/{ns}/{lng}.json';
};

export type GetTranslationResponses = {
    200: unknown;
};

export type LoginData = {
    body: LoginBody;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginResponses = {
    default: LoginDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type VerifyTotpData = {
    body: VerifyTotpBody;
    path?: never;
    query?: never;
    url: '/api/auth/verify-totp';
};

export type VerifyTotpResponses = {
    default: LoginDto;
};

export type VerifyTotpResponse = VerifyTotpResponses[keyof VerifyTotpResponses];

export type RegisterData = {
    body: RegisterBody;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterResponses = {
    default: RegisterDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    201: unknown;
};

export type RefreshSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/session/refresh';
};

export type RefreshSessionResponses = {
    default: SessionRefreshDto;
};

export type RefreshSessionResponse = RefreshSessionResponses[keyof RefreshSessionResponses];

export type StartPortalLoginData = {
    body?: never;
    path?: never;
    query: {
        redirect_url: string;
        desktop: string;
    };
    url: '/api/auth/portal/start';
};

export type StartPortalLoginResponses = {
    200: unknown;
};

export type PortalCallbackData = {
    body?: never;
    path?: never;
    query: {
        code: string;
        state: string;
    };
    url: '/api/auth/portal/callback';
};

export type PortalCallbackResponses = {
    200: unknown;
};

export type PortalSessionHintData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/portal/session-hint';
};

export type PortalSessionHintResponses = {
    default: PortalSessionHintDto;
};

export type PortalSessionHintResponse = PortalSessionHintResponses[keyof PortalSessionHintResponses];

export type ExchangePortalDesktopLoginData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/api/auth/portal/desktop-exchange';
};

export type ExchangePortalDesktopLoginResponses = {
    default: PortalDesktopExchangeDto;
};

export type ExchangePortalDesktopLoginResponse = ExchangePortalDesktopLoginResponses[keyof ExchangePortalDesktopLoginResponses];

export type ChangeUsernameData = {
    body: ChangeUsernameBody;
    path?: never;
    query?: never;
    url: '/api/auth/username';
};

export type ChangeUsernameResponses = {
    200: unknown;
};

export type ChangePasswordData = {
    body: ChangePasswordBody;
    path?: never;
    query?: never;
    url: '/api/auth/password';
};

export type ChangePasswordResponses = {
    200: unknown;
};

export type GetTotpUriData = {
    body: GetTotpUriBody;
    path?: never;
    query?: never;
    url: '/api/auth/totp/get-uri';
};

export type GetTotpUriResponses = {
    default: GetTotpUriDto;
};

export type GetTotpUriResponse = GetTotpUriResponses[keyof GetTotpUriResponses];

export type SetupTotpData = {
    body: SetupTotpBody;
    path?: never;
    query?: never;
    url: '/api/auth/totp/setup';
};

export type SetupTotpResponses = {
    200: unknown;
};

export type DisableTotpData = {
    body: DisableTotpBody;
    path?: never;
    query?: never;
    url: '/api/auth/totp/disable';
};

export type DisableTotpResponses = {
    200: unknown;
};

export type CancelResetPasswordData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type CancelResetPasswordResponses = {
    200: unknown;
};

export type CheckResetPasswordRequestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type CheckResetPasswordRequestResponses = {
    default: CheckResetPasswordRequestDto;
};

export type CheckResetPasswordRequestResponse = CheckResetPasswordRequestResponses[keyof CheckResetPasswordRequestResponses];

export type ResetPasswordData = {
    body: ResetPasswordBody;
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type ResetPasswordResponses = {
    default: ResetPasswordDto;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type RequestPasswordResetData = {
    body: PasswordResetRequestBody;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset/request';
};

export type RequestPasswordResetResponses = {
    default: PasswordResetRequestDto;
};

export type RequestPasswordResetResponse = RequestPasswordResetResponses[keyof RequestPasswordResetResponses];

export type VerifyPasswordResetTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset/verify/{token}';
};

export type VerifyPasswordResetTokenResponses = {
    default: PasswordResetVerifyResponseDto;
};

export type VerifyPasswordResetTokenResponse = VerifyPasswordResetTokenResponses[keyof VerifyPasswordResetTokenResponses];

export type CompletePasswordResetData = {
    body: PasswordResetCompleteBody;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset/complete';
};

export type CompletePasswordResetResponses = {
    default: PasswordResetCompleteDto;
};

export type CompletePasswordResetResponse = CompletePasswordResetResponses[keyof CompletePasswordResetResponses];

export type TraefikData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/traefik';
};

export type TraefikResponses = {
    200: unknown;
};

export type GetRehydratePlanData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/rehydrate/plan';
};

export type GetRehydratePlanResponses = {
    200: unknown;
};

export type GetRehydrateStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/rehydrate/status';
};

export type GetRehydrateStatusResponses = {
    200: unknown;
};

export type ExecuteRehydrateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/rehydrate';
};

export type ExecuteRehydrateResponses = {
    201: unknown;
};

export type InstallAppData = {
    body: AppFormBody;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/install';
};

export type InstallAppResponses = {
    default: LifecycleRequestDto;
};

export type InstallAppResponse = InstallAppResponses[keyof InstallAppResponses];

export type StartAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/start';
};

export type StartAppResponses = {
    default: LifecycleRequestDto;
};

export type StartAppResponse = StartAppResponses[keyof StartAppResponses];

export type StopAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/stop';
};

export type StopAppResponses = {
    default: LifecycleRequestDto;
};

export type StopAppResponse = StopAppResponses[keyof StopAppResponses];

export type ForceStopAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/force-stop';
};

export type ForceStopAppResponses = {
    default: LifecycleRequestDto;
};

export type ForceStopAppResponse = ForceStopAppResponses[keyof ForceStopAppResponses];

export type RestartAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/restart';
};

export type RestartAppResponses = {
    default: LifecycleRequestDto;
};

export type RestartAppResponse = RestartAppResponses[keyof RestartAppResponses];

export type UninstallAppData = {
    body: UninstallAppBody;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/uninstall';
};

export type UninstallAppResponses = {
    default: LifecycleRequestDto;
};

export type UninstallAppResponse = UninstallAppResponses[keyof UninstallAppResponses];

export type ResetAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/reset';
};

export type ResetAppResponses = {
    default: LifecycleRequestDto;
};

export type ResetAppResponse = ResetAppResponses[keyof ResetAppResponses];

export type UpdateAppData = {
    body: UpdateAppBody;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/update';
};

export type UpdateAppResponses = {
    default: LifecycleRequestDto;
};

export type UpdateAppResponse = UpdateAppResponses[keyof UpdateAppResponses];

export type UpdateAppConfigData = {
    body: AppFormBody;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/update-config';
};

export type UpdateAppConfigResponses = {
    default: LifecycleRequestDto;
};

export type UpdateAppConfigResponse = UpdateAppConfigResponses[keyof UpdateAppConfigResponses];

export type CancelOperationData = {
    body: CancelOperationBody;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/app-lifecycle/{urn}/cancel';
};

export type CancelOperationResponses = {
    default: CancelOperationResponseDto;
};

export type CancelOperationResponse = CancelOperationResponses[keyof CancelOperationResponses];

export type UpdateAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/update-all';
};

export type UpdateAllAppsResponses = {
    200: unknown;
};

export type StartAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/start-all';
};

export type StartAllAppsResponses = {
    201: unknown;
};

export type StopAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/stop-all';
};

export type StopAllAppsResponses = {
    201: unknown;
};

export type RestartAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/app-lifecycle/restart-all';
};

export type RestartAllAppsResponses = {
    201: unknown;
};

export type BackupAppData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/backups/{urn}/backup';
};

export type BackupAppResponses = {
    default: BackupRequestDto;
};

export type BackupAppResponse = BackupAppResponses[keyof BackupAppResponses];

export type RestoreAppBackupData = {
    body: RestoreAppBackupDto;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/backups/{urn}/restore';
};

export type RestoreAppBackupResponses = {
    default: BackupRequestDto;
};

export type RestoreAppBackupResponse = RestoreAppBackupResponses[keyof RestoreAppBackupResponses];

export type DeleteAppBackupData = {
    body: DeleteAppBackupBodyDto;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/backups/{urn}';
};

export type DeleteAppBackupResponses = {
    200: unknown;
};

export type GetAppBackupsData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/backups/{urn}';
};

export type GetAppBackupsResponses = {
    default: GetAppBackupsDto;
};

export type GetAppBackupsResponse = GetAppBackupsResponses[keyof GetAppBackupsResponses];

export type DownloadBackupData = {
    body?: never;
    path: {
        urn: string;
        filename: string;
    };
    query?: never;
    url: '/api/backups/{urn}/{filename}/download';
};

export type DownloadBackupResponses = {
    /**
     * Backup file download
     */
    200: unknown;
};

export type UploadBackupData = {
    body: {
        file?: Blob | File;
    };
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/backups/{urn}/upload';
};

export type UploadBackupResponses = {
    /**
     * Backup uploaded successfully
     */
    201: unknown;
};

export type AppEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sse/app';
};

export type AppEventsResponses = {
    200: unknown;
};

export type AppLogsEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sse/app-logs';
};

export type AppLogsEventsResponses = {
    200: unknown;
};

export type HubLogsEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sse/ci-hub-logs';
};

export type HubLogsEventsResponses = {
    200: unknown;
};

export type GetStatus4Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tailscale/status';
};

export type GetStatus4Responses = {
    default: {
        [key: string]: unknown;
    };
};

export type GetStatus4Response = GetStatus4Responses[keyof GetStatus4Responses];

export type SyncExposureData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tailscale/sync';
};

export type SyncExposureResponses = {
    /**
     * Sync triggered
     */
    200: unknown;
};

export type StartAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tailscale/auth/start';
};

export type StartAuthResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type StartAuthResponse = StartAuthResponses[keyof StartAuthResponses];

export type ConnectWithAuthKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tailscale/auth/key';
};

export type ConnectWithAuthKeyResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type ConnectWithAuthKeyResponse = ConnectWithAuthKeyResponses[keyof ConnectWithAuthKeyResponses];

export type CheckAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tailscale/auth/check';
};

export type CheckAuthResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type CheckAuthResponse = CheckAuthResponses[keyof CheckAuthResponses];

export type DisconnectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tailscale/disconnect';
};

export type DisconnectResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type DisconnectResponse = DisconnectResponses[keyof DisconnectResponses];

export type GetServeStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tailscale/serve';
};

export type GetServeStatusResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type GetServeStatusResponse = GetServeStatusResponses[keyof GetServeStatusResponses];

export type GetGuestLinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/links/guest';
};

export type GetGuestLinksResponses = {
    default: LinksDto;
};

export type GetGuestLinksResponse = GetGuestLinksResponses[keyof GetGuestLinksResponses];

export type GetLinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/links';
};

export type GetLinksResponses = {
    default: LinksDto;
};

export type GetLinksResponse = GetLinksResponses[keyof GetLinksResponses];

export type CreateLinkData = {
    body: LinkBodyDto;
    path?: never;
    query?: never;
    url: '/api/links';
};

export type CreateLinkResponses = {
    201: unknown;
};

export type DeleteLinkData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/links/{id}';
};

export type DeleteLinkResponses = {
    200: unknown;
};

export type EditLinkData = {
    body: EditLinkBodyDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/links/{id}';
};

export type EditLinkResponses = {
    200: unknown;
};

export type LiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/live';
};

export type LiveResponses = {
    200: unknown;
};

export type CheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type CheckErrors = {
    /**
     * The Health Check is not successful
     */
    503: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
    };
};

export type CheckError = CheckErrors[keyof CheckErrors];

export type CheckResponses = {
    /**
     * The Health Check is successful
     */
    200: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown | string;
            };
        };
    };
};

export type CheckResponse = CheckResponses[keyof CheckResponses];

export type CheckDataIntegrityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/data';
};

export type CheckDataIntegrityResponses = {
    200: unknown;
};

export type GetDiagnostics2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public-web/diagnostics';
};

export type GetDiagnostics2Responses = {
    default: {
        [key: string]: unknown;
    };
};

export type GetDiagnostics2Response = GetDiagnostics2Responses[keyof GetDiagnostics2Responses];

export type RepairData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public-web/repair';
};

export type RepairResponses = {
    default: {
        [key: string]: unknown;
    };
};

export type RepairResponse = RepairResponses[keyof RepairResponses];

export type GetUserConfigData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/user-config/{urn}';
};

export type GetUserConfigResponses = {
    default: GetUserConfigDto;
};

export type GetUserConfigResponse = GetUserConfigResponses[keyof GetUserConfigResponses];

export type UpdateUserConfigData = {
    body: UpdateUserConfigDto;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/user-config/{urn}';
};

export type UpdateUserConfigResponses = {
    200: unknown;
};

export type EnableUserConfigData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/user-config/{urn}/enable';
};

export type EnableUserConfigResponses = {
    201: unknown;
};

export type DisableUserConfigData = {
    body?: never;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/user-config/{urn}/disable';
};

export type DisableUserConfigResponses = {
    201: unknown;
};

export type CreateCustomAppData = {
    body: CreateCustomAppDto;
    path?: never;
    query?: never;
    url: '/api/custom-apps';
};

export type CreateCustomAppResponses = {
    default: CreateCustomAppResponseDto;
};

export type CreateCustomAppResponse = CreateCustomAppResponses[keyof CreateCustomAppResponses];

export type UpdateCustomAppData = {
    body: UpdateCustomAppDto;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/custom-apps/{urn}';
};

export type UpdateCustomAppResponses = {
    default: unknown;
};

export type UploadAppImageData = {
    body: {
        image?: Blob | File;
    };
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/custom-apps/{urn}/image';
};

export type UploadAppImageResponses = {
    /**
     * Logo uploaded successfully
     */
    200: unknown;
};

export type UpdateAppMetadataData = {
    body: UpdateAppMetadataDto;
    path: {
        urn: string;
    };
    query?: never;
    url: '/api/custom-apps/{urn}/metadata';
};

export type UpdateAppMetadataResponses = {
    default: unknown;
};

export type CheckForUpdatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/update/check';
};

export type CheckForUpdatesResponses = {
    200: unknown;
};

export type PerformUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/update';
};

export type PerformUpdateResponses = {
    201: unknown;
};

export type GetAutoUpdatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/update/auto-updates';
};

export type GetAutoUpdatesResponses = {
    200: unknown;
};

export type SetAutoUpdatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/update/auto-updates';
};

export type SetAutoUpdatesResponses = {
    201: unknown;
};

export type GetHostListenerTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/update/host-listener-token';
};

export type GetHostListenerTokenResponses = {
    200: unknown;
};

export type SeedDatabaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/seed';
};

export type SeedDatabaseResponses = {
    201: unknown;
};

export type SetAllAppUpdateAvailableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/set-all-app-update-available';
};

export type SetAllAppUpdateAvailableResponses = {
    201: unknown;
};

export type SetAllAppSubnetToNullData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/set-all-subnets-to-null';
};

export type SetAllAppSubnetToNullResponses = {
    201: unknown;
};

export type StartAllApps2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/start-all-apps';
};

export type StartAllApps2Responses = {
    201: unknown;
};

export type BackupAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/backup-all-apps';
};

export type BackupAllAppsResponses = {
    201: unknown;
};

export type IncrementAllAppVersionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/increment-all-app-versions';
};

export type IncrementAllAppVersionsResponses = {
    201: unknown;
};

export type UninstallAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/debug/uninstall-all-apps';
};

export type UninstallAllAppsResponses = {
    201: unknown;
};

export type SseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mcp/sse';
};

export type SseResponses = {
    200: unknown;
};

export type MessagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mcp/messages';
};

export type MessagesResponses = {
    201: unknown;
};
