services:
  ci-os-hub:
    ports:
      - "3000:3000"
    environment:
      - DEVICE_ID=${DEVICE_ID}
      - CI_CLOUD_FRONTEND_URL=${CI_CLOUD_FRONTEND_URL}
      - CI_CLOUD_API_URL=${CI_CLOUD_API_URL}
      - CI_HUB_ORGANIZATION_ID=${CI_HUB_ORGANIZATION_ID}
      - CI_HUB_API_KEY=${CI_HUB_API_KEY}

