services:
  ci-os-hub:
    environment:
      - DEVICE_ID=${DEVICE_ID}
      - CI_HUB_ORGANIZATION_ID=${CI_HUB_ORGANIZATION_ID}
    build:
      context: ${HOST_PATH}
    volumes:
      - ${HOST_PATH}/.internal/media:/data/media
      - ${HOST_PATH}/.internal/state:/data/state
      - ${HOST_PATH}/.internal/repos:/data/repos
      - ${HOST_PATH}/.internal/apps:/data/apps
      - ${HOST_PATH}/.internal/logs:/data/logs
      - ${HOST_PATH}/.internal/user-config:/data/user-config
      - ${HOST_PATH}/.internal/app-data:/app-data
      - ${HOST_PATH}/.internal/backups:/data/backups
      - ${HOST_PATH}/${ENV_FILE:-.env}:/data/.env:ro
      - ${HOST_PATH}/.internal/cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/meminfo:/host/proc/meminfo:ro
      - ${HOST_PATH}/docker-compose.prod.yml:/data/docker-compose.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
