services:
  ci-hub-db:
    container_name: ci-hub-db
    image: postgres:14
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - ci_hub_pgdata:/var/lib/postgresql/data
    command: -p 6543
    ports:
      - 6543:6543
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: tipi
      POSTGRES_DB: tipi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d tipi -U tipi -p 6543"]
      interval: 5s
      timeout: 10s
      retries: 120
    networks:
      - ci_os_hub_network

  ci-os-hub-queue:
    container_name: ci-os-hub-queue
    image: rabbitmq:4-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 60s
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: tipi
      RABBITMQ_DEFAULT_PASS: tipi
    networks:
      - ci_os_hub_network

  ci-os-hub:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npx turbo run dev --filter backend --filter @runtipi/common
    depends_on:
      ci-hub-db:
        condition: service_healthy
      ci-os-hub-queue:
        condition: service_healthy
    container_name: ci-os-hub
    restart: unless-stopped
    healthcheck:
      start_period: 30s
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - 3000:3000
      - 9091:9091
    volumes:
      # Hot reload
      - ./packages/backend/src:/app/packages/backend/src
      - ./packages/frontend/src:/app/packages/frontend/src
      - ./packages/common/src:/app/packages/common/src
      # Migrations
      - ./packages/backend/src/core/database/drizzle:/app/assets/migrations
      # Data
      - ${RUNTIPI_MEDIA_PATH:-.internal}/media:/data/media
      - ${RUNTIPI_STATE_PATH:-.internal}/state:/data/state
      - ${RUNTIPI_REPOS_PATH:-.internal}/repos:/data/repos
      - ../CI-App-Store:/data/repos/migrated
      - ${RUNTIPI_APPS_PATH:-.internal}/apps:/data/apps
      - ${RUNTIPI_LOGS_PATH:-.internal}/logs:/data/logs
      - ${RUNTIPI_USER_CONFIG_PATH:-.internal}/user-config:/data/user-config
      - ${RUNTIPI_APP_DATA_PATH:-.internal}/app-data:/app-data
      - ${RUNTIPI_BACKUPS_PATH:-.internal}/backups:/data/backups
      # Static
      - ${ENV_FILE:-.env}:/data/.env
      - ./.internal/cache:/cache
      - ./docker-compose.local.yml:/data/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/meminfo:/host/proc/meminfo:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - ci_os_hub_network
    environment:
      LOCAL: true
      NODE_ENV: development
      ROOT_FOLDER_HOST: ${PWD}/.internal
      POSTGRES_PASSWORD: postgres
      RABBITMQ_USERNAME: tipi
      RABBITMQ_PASSWORD: tipi
      RABBITMQ_HOST: ci-os-hub-queue
      INTERNAL_IP: 127.0.0.1
      TIPI_VERSION: 4.5.0
      LOG_LEVEL: debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: ${ENV_FILE:-.env}
        required: false
    labels:
      # ---- General ----- #
      ci-hub.managed: true

networks:
  ci_os_hub_network:
    driver: bridge
    name: ci-os-hub_network

volumes:
  ci_hub_pgdata:
