ARG NODE_VERSION="22"
ARG ALPINE_VERSION="3.21"

FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS base

# Install pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@9.15.0 --activate

RUN apk add --no-cache g++ make curl python3 openssl git docker-cli

ARG TARGETARCH
ARG DOCKER_COMPOSE_VERSION="v2.39.2"
ENV TARGETARCH=${TARGETARCH}
ENV NODE_ENV="development"

WORKDIR /app

RUN echo "Building for ${TARGETARCH}"
RUN if [ "${TARGETARCH}" = "arm64" ]; then \
  curl -L -o docker-binary "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-linux-aarch64"; \
  elif [ "${TARGETARCH}" = "amd64" ]; then \
  curl -L -o docker-binary "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-linux-x86_64"; \
  fi

RUN chmod +x docker-binary
RUN mv docker-binary /usr/local/bin/docker-compose

COPY ./package.json ./package.json
COPY ./pnpm-workspace.yaml ./
COPY ./pnpm-lock.yaml ./
COPY ./packages/backend/package.json ./packages/backend/package.json
COPY ./packages/frontend/package.json ./packages/frontend/package.json
COPY ./packages/common/package.json ./packages/common/package.json
COPY ./packages/frontend/scripts ./packages/frontend/scripts
COPY ./packages/frontend/public ./packages/frontend/public

RUN pnpm install --frozen-lockfile

COPY ./turbo.json ./turbo.json
COPY ./tsconfig.json ./tsconfig.json
COPY ./packages ./packages
COPY ./packages/backend/assets ./assets
COPY ./packages/backend/src/core/database/drizzle ./assets/migrations

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
