import type { CuratedModel } from '@ci-hub/common/types';

const QUANTS = [
  { suffix: 'fp16', name: 'FP16', mult: 3.2 },
  { suffix: 'q8_0', name: '8-bit', mult: 1.7 },
  { suffix: 'q6_K', name: '6-bit', mult: 1.3 },
  { suffix: 'q5_K_M', name: '5-bit', mult: 1.15 },
  { suffix: 'q4_K_M', name: '4-bit', mult: 1.0 },
  { suffix: 'q3_K_M', name: '3-bit', mult: 0.75 },
];

const BASE_LLMS: Array<
  Omit<CuratedModel, 'id' | 'backendModelId' | 'displayName' | 'backend'> & {
    baseId: string;
    baseBackendModelId: string;
    baseDisplayName: string;
  }
> = [
  {
    baseId: 'gemma4-27b',
    baseBackendModelId: 'gemma4:27b',
    modality: 'llm',
    purpose: 'general',
    baseDisplayName: 'Gemma 4 27B',
    description: 'Largest Gemma 4 option for high-end systems that need strongest local reasoning quality.',
    requirements: {
      minVramMb: 16384,
      recommendedVramMb: 49152,
      minRamMb: 49152,
      diskMb: 18432,
      gpuVendors: ['nvidia', 'amd', 'apple'],
      npuRequired: false,
      minTier: 'high',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      pinnedByDefault: false,
      memoryFootprintMb: 15000,
    },
    tiers: { high: 'recommended', medium: 'available', low: 'not-recommended', cpuOnly: 'not-recommended' },
  },
  {
    baseId: 'nemotron3-22b',
    baseBackendModelId: 'nemotron3:22b',
    modality: 'llm',
    purpose: 'reasoning',
    baseDisplayName: 'Nemotron 3 22B',
    description: 'Large Nemotron 3 option tuned for longer-form reasoning and instruction following.',
    requirements: {
      minVramMb: 12288,
      recommendedVramMb: 16384,
      minRamMb: 24576,
      diskMb: 14336,
      gpuVendors: ['nvidia', 'amd', 'apple'],
      npuRequired: false,
      minTier: 'high',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      pinnedByDefault: false,
      memoryFootprintMb: 12000,
    },
    tiers: { high: 'recommended', medium: 'available', low: 'not-recommended', cpuOnly: 'not-recommended' },
  },
  {
    baseId: 'qwen3-6-20b',
    baseBackendModelId: 'qwen3.6:20b',
    modality: 'llm',
    purpose: 'general',
    baseDisplayName: 'Qwen 3.6 20B',
    description: 'Balanced mid-large model. Recommended for ~12GB+ VRAM systems.',
    requirements: {
      minVramMb: 8192,
      recommendedVramMb: 12288,
      minRamMb: 24576,
      diskMb: 12288,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'medium',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      pinnedByDefault: false,
      memoryFootprintMb: 8192,
    },
    tiers: { high: 'recommended', medium: 'recommended', low: 'available', cpuOnly: 'not-recommended' },
  },
  {
    baseId: 'gemma4-12b',
    baseBackendModelId: 'gemma4:12b',
    modality: 'llm',
    purpose: 'general',
    baseDisplayName: 'Gemma 4 12B',
    description: 'Mid-size Gemma 4 option for common desktop GPUs and larger unified-memory systems.',
    requirements: {
      minVramMb: 4096,
      recommendedVramMb: 8192,
      minRamMb: 16384,
      diskMb: 7168,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'low',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      pinnedByDefault: false,
      memoryFootprintMb: 6200,
    },
    tiers: { high: 'available', medium: 'recommended', low: 'recommended', cpuOnly: 'available' },
  },
  {
    baseId: 'qwen3-6-8b',
    baseBackendModelId: 'qwen3.6:8b',
    modality: 'llm',
    purpose: 'coding',
    baseDisplayName: 'Qwen 3.6 8B',
    description: 'Compact Qwen 3.6 model with strong coding and assistant behavior for lower VRAM systems.',
    requirements: {
      minVramMb: 4096,
      recommendedVramMb: 4096,
      minRamMb: 8192,
      diskMb: 5120,
      gpuVendors: ['nvidia', 'amd', 'apple', 'intel', 'cpu'],
      npuRequired: false,
      minTier: 'low',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 4096,
      reasoning: true,
      input: ['text'],
      pinnedByDefault: false,
      memoryFootprintMb: 4600,
    },
    tiers: { high: 'available', medium: 'recommended', low: 'recommended', cpuOnly: 'available' },
  },
  {
    baseId: 'nemotron3-8b',
    baseBackendModelId: 'nemotron3:8b',
    modality: 'llm',
    purpose: 'reasoning',
    baseDisplayName: 'Nemotron 3 8B',
    description: 'Small Nemotron 3 variant focused on efficient reasoning under constrained resources.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 4096,
      minRamMb: 8192,
      diskMb: 5632,
      gpuVendors: ['nvidia', 'amd', 'apple', 'intel', 'cpu'],
      npuRequired: false,
      minTier: 'low',
    },
    runtime: {
      contextWindow: 262144,
      maxTokens: 4096,
      reasoning: true,
      input: ['text'],
      pinnedByDefault: false,
      memoryFootprintMb: 5000,
    },
    tiers: { high: 'available', medium: 'available', low: 'recommended', cpuOnly: 'available' },
  },
  {
    baseId: 'gemma4-4b',
    baseBackendModelId: 'gemma4:4b',
    modality: 'llm',
    purpose: 'fast',
    baseDisplayName: 'Gemma 4 4B',
    description: 'Fast smallest Gemma 4 option for CPU-only and integrated-GPU systems.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 4096,
      minRamMb: 6144,
      diskMb: 3072,
      gpuVendors: ['nvidia', 'amd', 'apple', 'intel', 'cpu'],
      npuRequired: false,
      minTier: 'cpu-only',
    },
    runtime: {
      contextWindow: 65536,
      maxTokens: 4096,
      reasoning: false,
      input: ['text'],
      pinnedByDefault: true,
      memoryFootprintMb: 2900,
    },
    tiers: { high: 'available', medium: 'available', low: 'recommended', cpuOnly: 'recommended' },
  },
];

const generatedLlms: CuratedModel[] = [];

for (const base of BASE_LLMS) {
  for (const q of QUANTS) {
    const isQ4 = q.suffix === 'q4_K_M';
    generatedLlms.push({
      id: isQ4 ? base.baseId : `${base.baseId}-${q.suffix}`,
      backend: 'ollama',
      backendModelId: isQ4 ? base.baseBackendModelId : `${base.baseBackendModelId}-${q.suffix}`,
      modality: base.modality,
      purpose: base.purpose,
      displayName: isQ4 ? base.baseDisplayName : `${base.baseDisplayName} (${q.name})`,
      description: base.description,
      requirements: {
        ...base.requirements,
        minVramMb: Math.round(base.requirements.minVramMb * q.mult),
        recommendedVramMb: Math.round(base.requirements.recommendedVramMb * q.mult),
        minRamMb: Math.round(base.requirements.minRamMb * q.mult),
        diskMb: Math.round(base.requirements.diskMb * q.mult),
      },
      runtime: {
        ...base.runtime,
        quantization: q.suffix,
        pinnedByDefault: isQ4 ? base.runtime.pinnedByDefault : false,
        memoryFootprintMb: Math.round(base.runtime.memoryFootprintMb * q.mult),
      },
      tiers: base.tiers,
    });
  }
}

const VOICE_MODELS: CuratedModel[] = [
  {
    id: 'kokoro-v1',
    backend: 'lemonade',
    backendModelId: 'kokoro-v1',
    modality: 'tts',
    purpose: 'voice',
    displayName: 'Kokoro v1 TTS',
    description: 'High-quality text-to-speech. Low latency, natural sounding.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 512,
      minRamMb: 1024,
      diskMb: 300,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'cpu-only',
    },
    runtime: {
      contextWindow: 0,
      maxTokens: 0,
      reasoning: false,
      input: ['text'],
      pinnedByDefault: true,
      memoryFootprintMb: 350,
    },
    tiers: { high: 'recommended', medium: 'recommended', low: 'recommended', cpuOnly: 'recommended' },
  },
  {
    id: 'whisper-large-v3-turbo',
    backend: 'lemonade',
    backendModelId: 'whisper-large-v3-turbo',
    modality: 'stt',
    purpose: 'transcription',
    displayName: 'Whisper Large v3 Turbo',
    description: "OpenAI's speech-to-text model. Fast and accurate transcription.",
    requirements: {
      minVramMb: 4096,
      recommendedVramMb: 6144,
      minRamMb: 8192,
      diskMb: 1500,
      gpuVendors: ['nvidia', 'amd', 'apple'],
      npuRequired: false,
      minTier: 'medium',
    },
    runtime: {
      contextWindow: 0,
      maxTokens: 0,
      reasoning: false,
      input: ['audio'],
      pinnedByDefault: false,
      memoryFootprintMb: 1500,
    },
    tiers: { high: 'recommended', medium: 'recommended', low: 'not-recommended', cpuOnly: 'not-recommended' },
  },
  {
    id: 'whisper-base',
    backend: 'lemonade',
    backendModelId: 'whisper-base',
    modality: 'stt',
    purpose: 'transcription',
    displayName: 'Whisper Base',
    description: 'Lightweight speech-to-text for resource-constrained environments.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 512,
      minRamMb: 1024,
      diskMb: 150,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'cpu-only',
    },
    runtime: {
      contextWindow: 0,
      maxTokens: 0,
      reasoning: false,
      input: ['audio'],
      pinnedByDefault: false,
      memoryFootprintMb: 200,
    },
    tiers: { high: 'available', medium: 'available', low: 'recommended', cpuOnly: 'recommended' },
  },
];

export const CURATED_MODELS: CuratedModel[] = [...generatedLlms, ...VOICE_MODELS];
