import type { CuratedModel } from '@ci-hub/common/types';

/**
 * Curated model catalog — models approved for the Hub with hardware requirements and tier recommendations.
 * This is NOT an open-ended model browser — it's a curated list mapping hardware tiers to recommended models.
 */
export const CURATED_MODELS: CuratedModel[] = [
  // ─── High-Tier LLMs ─────────────────────────────────────────────────────
  {
    id: 'llama4-scout',
    backend: 'ollama',
    backendModelId: 'llama4:16x17b',
    modality: 'llm',
    purpose: 'general',
    displayName: 'Llama 4 Scout',
    description: "Meta's latest multimodal MoE model. 109B total / 17B active params. Vision + text with 10M context.",
    requirements: {
      minVramMb: 24576,
      recommendedVramMb: 49152,
      minRamMb: 65536,
      diskMb: 68000,
      gpuVendors: ['nvidia', 'amd', 'apple'],
      npuRequired: false,
      minTier: 'high',
    },
    runtime: {
      contextWindow: 10000000,
      maxTokens: 8192,
      reasoning: false,
      input: ['text', 'image'],
      quantization: 'Q4_K_M',
      pinnedByDefault: true,
      memoryFootprintMb: 42000,
    },
    tiers: { high: 'recommended', medium: 'not-recommended', low: 'not-recommended', cpuOnly: 'not-recommended' },
  },
  {
    id: 'qwen3-coder-30b',
    backend: 'ollama',
    backendModelId: 'qwen3-coder:30b',
    modality: 'llm',
    purpose: 'coding',
    displayName: 'Qwen 3 Coder 30B',
    description: "Alibaba's top agentic code model. MoE 30B / 3.3B active. 256K context, execution-driven RL.",
    requirements: {
      minVramMb: 12288,
      recommendedVramMb: 24576,
      minRamMb: 24576,
      diskMb: 20480,
      gpuVendors: ['nvidia', 'amd', 'apple'],
      npuRequired: false,
      minTier: 'high',
    },
    runtime: {
      contextWindow: 262144,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: false,
      memoryFootprintMb: 20000,
    },
    tiers: { high: 'recommended', medium: 'not-recommended', low: 'not-recommended', cpuOnly: 'not-recommended' },
  },

  // ─── Medium-Tier LLMs ───────────────────────────────────────────────────
  {
    id: 'qwen3-14b',
    backend: 'ollama',
    backendModelId: 'qwen3:14b',
    modality: 'llm',
    purpose: 'general',
    displayName: 'Qwen 3 14B',
    description: 'Dense 14B with thinking/non-thinking modes. Outperforms much larger models on reasoning.',
    requirements: {
      minVramMb: 8192,
      recommendedVramMb: 12288,
      minRamMb: 12288,
      diskMb: 10240,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'medium',
    },
    runtime: {
      contextWindow: 40960,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: true,
      memoryFootprintMb: 9800,
    },
    tiers: { high: 'available', medium: 'recommended', low: 'not-recommended', cpuOnly: 'not-recommended' },
  },
  {
    id: 'qwen3-8b',
    backend: 'ollama',
    backendModelId: 'qwen3:8b',
    modality: 'llm',
    purpose: 'coding',
    displayName: 'Qwen 3 8B',
    description: 'Dense 8B with thinking mode. Strong code and reasoning for its size.',
    requirements: {
      minVramMb: 4096,
      recommendedVramMb: 8192,
      minRamMb: 8192,
      diskMb: 5632,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'medium',
    },
    runtime: {
      contextWindow: 40960,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: false,
      memoryFootprintMb: 5500,
    },
    tiers: { high: 'available', medium: 'recommended', low: 'available', cpuOnly: 'not-recommended' },
  },

  // ─── Low-Tier / CPU LLMs ────────────────────────────────────────────────
  {
    id: 'phi-4-mini',
    backend: 'ollama',
    backendModelId: 'phi4-mini',
    modality: 'llm',
    purpose: 'general',
    displayName: 'Phi-4 Mini',
    description: "Microsoft's compact 3.8B model. 128K context, strong reasoning. Runs well on CPU.",
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 4096,
      minRamMb: 4096,
      diskMb: 2560,
      gpuVendors: ['nvidia', 'amd', 'apple', 'intel', 'cpu'],
      npuRequired: false,
      minTier: 'cpu-only',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 4096,
      reasoning: false,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: true,
      memoryFootprintMb: 2600,
    },
    tiers: { high: 'available', medium: 'available', low: 'recommended', cpuOnly: 'recommended' },
  },
  {
    id: 'qwen3-4b',
    backend: 'ollama',
    backendModelId: 'qwen3:4b',
    modality: 'llm',
    purpose: 'coding',
    displayName: 'Qwen 3 4B',
    description: 'Compact 4B with 256K context and thinking mode. Rivals Qwen 2.5 72B performance.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 4096,
      minRamMb: 4096,
      diskMb: 2816,
      gpuVendors: ['nvidia', 'amd', 'apple', 'intel', 'cpu'],
      npuRequired: false,
      minTier: 'low',
    },
    runtime: {
      contextWindow: 262144,
      maxTokens: 4096,
      reasoning: true,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: false,
      memoryFootprintMb: 2800,
    },
    tiers: { high: 'available', medium: 'available', low: 'recommended', cpuOnly: 'available' },
  },

  // ─── Voice Models ───────────────────────────────────────────────────────
  {
    id: 'kokoro-v1',
    backend: 'lemonade',
    backendModelId: 'kokoro-v1',
    modality: 'tts',
    purpose: 'voice',
    displayName: 'Kokoro v1 TTS',
    description: 'High-quality text-to-speech. Low latency, natural sounding.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 512,
      minRamMb: 1024,
      diskMb: 300,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'cpu-only',
    },
    runtime: {
      contextWindow: 0,
      maxTokens: 0,
      reasoning: false,
      input: ['text'],
      pinnedByDefault: true,
      memoryFootprintMb: 350,
    },
    tiers: { high: 'recommended', medium: 'recommended', low: 'recommended', cpuOnly: 'recommended' },
  },
  {
    id: 'whisper-large-v3-turbo',
    backend: 'lemonade',
    backendModelId: 'whisper-large-v3-turbo',
    modality: 'stt',
    purpose: 'transcription',
    displayName: 'Whisper Large v3 Turbo',
    description: "OpenAI's speech-to-text model. Fast and accurate transcription.",
    requirements: {
      minVramMb: 4096,
      recommendedVramMb: 6144,
      minRamMb: 8192,
      diskMb: 1500,
      gpuVendors: ['nvidia', 'amd', 'apple'],
      npuRequired: false,
      minTier: 'medium',
    },
    runtime: {
      contextWindow: 0,
      maxTokens: 0,
      reasoning: false,
      input: ['audio'],
      pinnedByDefault: false,
      memoryFootprintMb: 1500,
    },
    tiers: { high: 'recommended', medium: 'recommended', low: 'not-recommended', cpuOnly: 'not-recommended' },
  },
  {
    id: 'whisper-base',
    backend: 'lemonade',
    backendModelId: 'whisper-base',
    modality: 'stt',
    purpose: 'transcription',
    displayName: 'Whisper Base',
    description: 'Lightweight speech-to-text for resource-constrained environments.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 512,
      minRamMb: 1024,
      diskMb: 150,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'cpu-only',
    },
    runtime: {
      contextWindow: 0,
      maxTokens: 0,
      reasoning: false,
      input: ['audio'],
      pinnedByDefault: false,
      memoryFootprintMb: 200,
    },
    tiers: { high: 'available', medium: 'available', low: 'recommended', cpuOnly: 'recommended' },
  },
];
