import type { CuratedModel } from '@ci-hub/common/types';

/**
 * Curated model catalog — models approved for the Hub with hardware requirements and tier recommendations.
 * This is NOT an open-ended model browser — it's a curated list mapping hardware tiers to recommended models.
 */
export const CURATED_MODELS: CuratedModel[] = [
  // ─── Ollama LLMs (Gemma 4, Qwen 3.6, Nemotron 3) ─────────────────────
  {
    id: 'gemma4-27b',
    backend: 'ollama',
    backendModelId: 'gemma4:27b',
    modality: 'llm',
    purpose: 'general',
    displayName: 'Gemma 4 27B',
    description: 'Largest Gemma 4 option for high-end systems that need strongest local reasoning quality.',
    requirements: {
      minVramMb: 16384,
      recommendedVramMb: 49152,
      minRamMb: 49152,
      diskMb: 18432,
      gpuVendors: ['nvidia', 'amd', 'apple'],
      npuRequired: false,
      minTier: 'high',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: false,
      memoryFootprintMb: 15000,
    },
    tiers: { high: 'recommended', medium: 'available', low: 'not-recommended', cpuOnly: 'not-recommended' },
  },
  {
    id: 'nemotron3-22b',
    backend: 'ollama',
    backendModelId: 'nemotron3:22b',
    modality: 'llm',
    purpose: 'reasoning',
    displayName: 'Nemotron 3 22B',
    description: 'Large Nemotron 3 option tuned for longer-form reasoning and instruction following.',
    requirements: {
      minVramMb: 12288,
      recommendedVramMb: 16384,
      minRamMb: 24576,
      diskMb: 14336,
      gpuVendors: ['nvidia', 'amd', 'apple'],
      npuRequired: false,
      minTier: 'high',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: false,
      memoryFootprintMb: 12000,
    },
    tiers: { high: 'recommended', medium: 'available', low: 'not-recommended', cpuOnly: 'not-recommended' },
  },
  {
    id: 'qwen3-6-20b',
    backend: 'ollama',
    backendModelId: 'qwen3.6:20b',
    modality: 'llm',
    purpose: 'general',
    displayName: 'Qwen 3.6 20B',
    description: 'Balanced mid-large model. Recommended for ~12GB+ VRAM systems.',
    requirements: {
      minVramMb: 8192,
      recommendedVramMb: 12288,
      minRamMb: 24576,
      diskMb: 12288,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'medium',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: false,
      memoryFootprintMb: 8192,
    },
    tiers: { high: 'recommended', medium: 'recommended', low: 'available', cpuOnly: 'not-recommended' },
  },
  {
    id: 'gemma4-12b',
    backend: 'ollama',
    backendModelId: 'gemma4:12b',
    modality: 'llm',
    purpose: 'general',
    displayName: 'Gemma 4 12B',
    description: 'Mid-size Gemma 4 option for common desktop GPUs and larger unified-memory systems.',
    requirements: {
      minVramMb: 4096,
      recommendedVramMb: 8192,
      minRamMb: 16384,
      diskMb: 7168,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'low',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 8192,
      reasoning: true,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: false,
      memoryFootprintMb: 6200,
    },
    tiers: { high: 'available', medium: 'recommended', low: 'recommended', cpuOnly: 'available' },
  },
  {
    id: 'qwen3-6-8b',
    backend: 'ollama',
    backendModelId: 'qwen3.6:8b',
    modality: 'llm',
    purpose: 'coding',
    displayName: 'Qwen 3.6 8B',
    description: 'Compact Qwen 3.6 model with strong coding and assistant behavior for lower VRAM systems.',
    requirements: {
      minVramMb: 4096,
      recommendedVramMb: 4096,
      minRamMb: 8192,
      diskMb: 5120,
      gpuVendors: ['nvidia', 'amd', 'apple', 'intel', 'cpu'],
      npuRequired: false,
      minTier: 'low',
    },
    runtime: {
      contextWindow: 131072,
      maxTokens: 4096,
      reasoning: true,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: false,
      memoryFootprintMb: 4600,
    },
    tiers: { high: 'available', medium: 'recommended', low: 'recommended', cpuOnly: 'available' },
  },
  {
    id: 'nemotron3-8b',
    backend: 'ollama',
    backendModelId: 'nemotron3:8b',
    modality: 'llm',
    purpose: 'reasoning',
    displayName: 'Nemotron 3 8B',
    description: 'Small Nemotron 3 variant focused on efficient reasoning under constrained resources.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 4096,
      minRamMb: 8192,
      diskMb: 5632,
      gpuVendors: ['nvidia', 'amd', 'apple', 'intel', 'cpu'],
      npuRequired: false,
      minTier: 'low',
    },
    runtime: {
      contextWindow: 262144,
      maxTokens: 4096,
      reasoning: true,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: false,
      memoryFootprintMb: 5000,
    },
    tiers: { high: 'available', medium: 'available', low: 'recommended', cpuOnly: 'available' },
  },
  {
    id: 'gemma4-4b',
    backend: 'ollama',
    backendModelId: 'gemma4:4b',
    modality: 'llm',
    purpose: 'fast',
    displayName: 'Gemma 4 4B',
    description: 'Fast smallest Gemma 4 option for CPU-only and integrated-GPU systems.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 4096,
      minRamMb: 6144,
      diskMb: 3072,
      gpuVendors: ['nvidia', 'amd', 'apple', 'intel', 'cpu'],
      npuRequired: false,
      minTier: 'cpu-only',
    },
    runtime: {
      contextWindow: 65536,
      maxTokens: 4096,
      reasoning: false,
      input: ['text'],
      quantization: 'Q4_K_M',
      pinnedByDefault: true,
      memoryFootprintMb: 2900,
    },
    tiers: { high: 'available', medium: 'available', low: 'recommended', cpuOnly: 'recommended' },
  },

  // ─── Voice Models ───────────────────────────────────────────────────────
  {
    id: 'kokoro-v1',
    backend: 'lemonade',
    backendModelId: 'kokoro-v1',
    modality: 'tts',
    purpose: 'voice',
    displayName: 'Kokoro v1 TTS',
    description: 'High-quality text-to-speech. Low latency, natural sounding.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 512,
      minRamMb: 1024,
      diskMb: 300,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'cpu-only',
    },
    runtime: {
      contextWindow: 0,
      maxTokens: 0,
      reasoning: false,
      input: ['text'],
      pinnedByDefault: true,
      memoryFootprintMb: 350,
    },
    tiers: { high: 'recommended', medium: 'recommended', low: 'recommended', cpuOnly: 'recommended' },
  },
  {
    id: 'whisper-large-v3-turbo',
    backend: 'lemonade',
    backendModelId: 'whisper-large-v3-turbo',
    modality: 'stt',
    purpose: 'transcription',
    displayName: 'Whisper Large v3 Turbo',
    description: "OpenAI's speech-to-text model. Fast and accurate transcription.",
    requirements: {
      minVramMb: 4096,
      recommendedVramMb: 6144,
      minRamMb: 8192,
      diskMb: 1500,
      gpuVendors: ['nvidia', 'amd', 'apple'],
      npuRequired: false,
      minTier: 'medium',
    },
    runtime: {
      contextWindow: 0,
      maxTokens: 0,
      reasoning: false,
      input: ['audio'],
      pinnedByDefault: false,
      memoryFootprintMb: 1500,
    },
    tiers: { high: 'recommended', medium: 'recommended', low: 'not-recommended', cpuOnly: 'not-recommended' },
  },
  {
    id: 'whisper-base',
    backend: 'lemonade',
    backendModelId: 'whisper-base',
    modality: 'stt',
    purpose: 'transcription',
    displayName: 'Whisper Base',
    description: 'Lightweight speech-to-text for resource-constrained environments.',
    requirements: {
      minVramMb: 0,
      recommendedVramMb: 512,
      minRamMb: 1024,
      diskMb: 150,
      gpuVendors: ['nvidia', 'amd', 'apple', 'cpu'],
      npuRequired: false,
      minTier: 'cpu-only',
    },
    runtime: {
      contextWindow: 0,
      maxTokens: 0,
      reasoning: false,
      input: ['audio'],
      pinnedByDefault: false,
      memoryFootprintMb: 200,
    },
    tiers: { high: 'available', medium: 'available', low: 'recommended', cpuOnly: 'recommended' },
  },
];
