import type { ZodDto } from '@/common/zod-dto';
import { AcknowledgeWelcomeBody, AppContextDto, UserContextDto, UserSettingsBody } from './app.dto';
import { StreamAppLogsQueryDto, StreamHubLogsQueryDto } from './core/sse/dto/sse.dto';
import { CreateApiKeyBody, UpdateApiKeyBody } from './modules/api-keys/api-key-admin.dto';
import {
  BrowserHandoffMintBody,
  BrowserHandoffMintDto,
  ChangePasswordBody,
  ChangeUsernameBody,
  CheckResetPasswordRequestDto,
  DisableTotpBody,
  GetTotpUriBody,
  GetTotpUriDto,
  LoginBody,
  LoginDto,
  PasswordResetCompleteBody,
  PasswordResetCompleteDto,
  PasswordResetRequestBody,
  PasswordResetRequestDto,
  PasswordResetVerifyResponseDto,
  PortalDesktopExchangeDto,
  PortalSessionHintDto,
  RegisterBody,
  RegisterDto,
  ResetPasswordBody,
  ResetPasswordDto,
  SessionRefreshDto,
  SetupTotpBody,
  VerifyTotpBody,
} from './modules/auth/dto/auth.dto';
import {
  AppFormBody,
  CancelOperationBody,
  CancelOperationResponseDto,
  LifecycleRequestDto,
  ResetAppBody,
  UninstallAppBody,
  UpdateAppBody,
  ValidateConfigResultDto as LifecycleValidateConfigResultDto,
} from './modules/app-lifecycle/dto/app-lifecycle.dto';
import {
  AppDataListingDto,
  GetAppDto,
  GetComposeDiffDto,
  GetConfigDiffDto,
  GetRandomPortDto,
  GuestAppsDto,
  InstalledAppUrnsDto,
  MyAppsDto,
  UpdatesAvailableDto,
} from './modules/apps/dto/app.dto';
import { InstallQueueDto } from './modules/apps/dto/install-queue.dto';
import { AppRuntimeHealthDto, AppRuntimeMonitorDto } from './modules/apps/dto/runtime-health.dto';
import { BackupRequestDto, DeleteAppBackupBodyDto, GetAppBackupsDto, RestoreAppBackupDto } from './modules/backups/dto/backups.dto';
import {
  CreateCustomAppDto,
  CreateCustomAppResponseDto,
  CreatePortExposeAppDto,
  UpdateAppMetadataDto,
  UpdateCustomAppDto,
  UpdatePortExposeAppDto,
} from './modules/custom-apps/dto/custom-apps.dto';
import {
  OnboardingProfileQueryDto,
  RuntimeModelsQueryDto,
  UpdateInferencePreferencesBody,
  UpdateRocmInstallStateBody,
} from './modules/inference/inference.dto';
import {
  DeletePoolPinQuery,
  PairingUpgradeBody,
  ProbePeerAddressBody,
  RoutingLogQueryDto,
  UpdateHubPoolPreferencesBody,
  UpsertPoolPinBody,
} from './modules/hub-pool/hub-pool.dto';
import { EditLinkBodyDto, LinkBodyDto, LinksDto } from './modules/links/dto/links.dto';
import {
  AllAppStoresDto,
  AppMediaDto,
  AppStoreDto,
  CreateAppStoreBodyDto,
  MetadataDto,
  PullDto,
  SearchAppsDto,
  SearchAppsQueryDto,
  UpdateAppStoreBodyDto,
  UpdateAppStoreDto,
} from './modules/marketplace/dto/marketplace.dto';
import { McpToolCallBody } from './modules/mcp/mcp-admin.dto';
import { McpInstallSchemaDto, McpProbeResultDto, ValidateConfigResultDto } from './modules/mcp/dto/mcp-app.dto';
import { FactoryResetDto } from './modules/system/dto/factory-reset.dto';
import { LoadDto, SystemResourcesDto } from './modules/system/dto/system.dto';
import { DesktopReleaseDto } from './modules/system-update/dto/desktop-release.dto';
import { GetUserConfigDto, UpdateUserConfigDto } from './modules/user-config/dto/user-config.dto';
import { PublicWebRepairBody } from './modules/public-web/public-web.dto';

/** Every Zod-backed DTO referenced in OpenAPI `components.schemas`. */
export const SWAGGER_ZOD_DTOS: ZodDto[] = [
  AppDataListingDto,
  AcknowledgeWelcomeBody,
  AppContextDto,
  UserContextDto,
  UserSettingsBody,
  StreamAppLogsQueryDto,
  StreamHubLogsQueryDto,
  CreateApiKeyBody,
  UpdateApiKeyBody,
  BrowserHandoffMintBody,
  BrowserHandoffMintDto,
  ChangePasswordBody,
  ChangeUsernameBody,
  CheckResetPasswordRequestDto,
  DisableTotpBody,
  GetTotpUriBody,
  GetTotpUriDto,
  LoginBody,
  LoginDto,
  PasswordResetCompleteBody,
  PasswordResetCompleteDto,
  PasswordResetRequestBody,
  PasswordResetRequestDto,
  PasswordResetVerifyResponseDto,
  PortalDesktopExchangeDto,
  PortalSessionHintDto,
  RegisterBody,
  RegisterDto,
  ResetPasswordBody,
  ResetPasswordDto,
  SessionRefreshDto,
  SetupTotpBody,
  VerifyTotpBody,
  AppFormBody,
  CancelOperationBody,
  CancelOperationResponseDto,
  LifecycleRequestDto,
  ResetAppBody,
  UninstallAppBody,
  UpdateAppBody,
  LifecycleValidateConfigResultDto,
  GetAppDto,
  GetComposeDiffDto,
  GetConfigDiffDto,
  GetRandomPortDto,
  GuestAppsDto,
  InstalledAppUrnsDto,
  UpdatesAvailableDto,
  MyAppsDto,
  InstallQueueDto,
  AppRuntimeHealthDto,
  AppRuntimeMonitorDto,
  BackupRequestDto,
  DeleteAppBackupBodyDto,
  GetAppBackupsDto,
  RestoreAppBackupDto,
  CreateCustomAppDto,
  CreateCustomAppResponseDto,
  CreatePortExposeAppDto,
  UpdateAppMetadataDto,
  UpdateCustomAppDto,
  UpdatePortExposeAppDto,
  OnboardingProfileQueryDto,
  RuntimeModelsQueryDto,
  UpdateInferencePreferencesBody,
  UpdateRocmInstallStateBody,
  PairingUpgradeBody,
  UpdateHubPoolPreferencesBody,
  ProbePeerAddressBody,
  RoutingLogQueryDto,
  UpsertPoolPinBody,
  DeletePoolPinQuery,
  EditLinkBodyDto,
  LinkBodyDto,
  LinksDto,
  AllAppStoresDto,
  AppMediaDto,
  AppStoreDto,
  CreateAppStoreBodyDto,
  MetadataDto,
  PullDto,
  SearchAppsDto,
  SearchAppsQueryDto,
  UpdateAppStoreBodyDto,
  UpdateAppStoreDto,
  McpToolCallBody,
  McpInstallSchemaDto,
  McpProbeResultDto,
  ValidateConfigResultDto,
  FactoryResetDto,
  LoadDto,
  SystemResourcesDto,
  DesktopReleaseDto,
  GetUserConfigDto,
  UpdateUserConfigDto,
  PublicWebRepairBody,
];
