await Bun.build({
  entrypoints: ['./src/main.ts'],
  outdir: './dist',
  format: 'esm',
  target: 'node',
  sourcemap: true,
  minify: false,
  external: [
    'argon2',
    'class-transformer',
    '@nestjs/typeorm',
    '@nestjs/mongoose',
    '@nestjs/sequelize',
    '@mikro-orm/core',
    '@fastify/static',
    '@nestjs/microservices',
    '@nestjs/websockets',
    'cpu-features',
    'drizzle-orm',
    '@opentelemetry/api',
  ],
});
