#!/usr/bin/env tsx
/**
 * Regenerates docs/agent/TEST_INVENTORY.md from test/spec files.
 * Usage: pnpm run agent:test-inventory
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '../..');
const OUT = join(ROOT, 'docs/agent/TEST_INVENTORY.md');

type Entry = { path: string; kind: string; hint: string };

function walk(dir: string, pattern: RegExp, acc: Entry[], kind: string): void {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (name === 'node_modules' || name === 'dist' || name === '.git') continue;
      walk(full, pattern, acc, kind);
      continue;
    }
    if (!pattern.test(name)) continue;
    const rel = relative(ROOT, full);
    const content = readFileSync(full, 'utf8');
    const describe = content.match(/describe\(['"`]([^'"`]+)['"`]/);
    const firstIt = content.match(/it\(['"`]([^'"`]+)['"`]/);
    const hint = describe?.[1] ?? firstIt?.[1] ?? '(see file)';
    acc.push({ path: rel, kind, hint });
  }
}

const entries: Entry[] = [];
walk(join(ROOT, 'e2e'), /\.spec\.ts$/, entries, 'e2e');
walk(join(ROOT, 'packages'), /\.(test|spec)\.(ts|tsx)$/, entries, 'unit');
walk(join(ROOT, 'scripts'), /\.test\.ts$/, entries, 'cli');

entries.sort((a, b) => a.path.localeCompare(b.path));

const byKind = {
  e2e: entries.filter((e) => e.kind === 'e2e'),
  unit: entries.filter((e) => e.kind === 'unit'),
  cli: entries.filter((e) => e.kind === 'cli'),
};

function table(rows: Entry[]): string {
  if (rows.length === 0) return '_None found._\n';
  return rows.map((e) => `| \`${e.path}\` | ${e.hint.replace(/\|/g, '\\|')} |`).join('\n') + '\n';
}

const md = `# Test Inventory — CI-Hub

> **Purpose:** Every test/spec file and a one-line description of what it covers.
> **Scope:** E2E Playwright specs, Vitest unit tests, CLI tests.
> **Regenerate:** \`pnpm run agent:test-inventory\`
> **Guide:** [TESTING.md](TESTING.md)
> **Router:** [AGENTS.md](../../AGENTS.md)
> **Last updated:** ${new Date().toISOString().slice(0, 10)}
> **Related:** docs/system/e2e.md, e2e/README.md

_Auto-generated by \`scripts/agent/generate-test-inventory.ts\`. Edit describe/it names in source files, then regenerate._

---

## E2E (${byKind.e2e.length})

| File | Covers |
|------|--------|
${table(byKind.e2e)}
---

## Unit / integration (${byKind.unit.length})

| File | Covers |
|------|--------|
${table(byKind.unit)}
---

## CLI (${byKind.cli.length})

| File | Covers |
|------|--------|
${table(byKind.cli)}
`;

writeFileSync(OUT, md);
console.log(`Wrote ${relative(ROOT, OUT)} (${entries.length} entries)`);
