#!/usr/bin/env tsx
/**
 * Bake the files a fresh appliance needs into the CLI, so a standalone `cihub` can seed an install
 * on a machine that has neither a checkout nor the desktop package.
 *
 * `seedApplianceInstall` looks for `docker-compose.prod.yml` next to the binary, in the desktop
 * package's resources, in `/usr/share/companion-hub`, or in a checkout — and a headless box has
 * none of those. On 2026-09-18 that was twelve of fifteen fleet nodes; the three that had a desktop
 * package had a July one, and the seed silently used its compose. Bun's `--compile` cannot carry
 * loose files, so the sources are rendered into a TypeScript module the binary imports.
 *
 * Usage:
 *   pnpm exec tsx scripts/generate-bundled-hub-assets.ts          # (re)write the module
 *   pnpm exec tsx scripts/generate-bundled-hub-assets.ts --check  # exit 1 if it is stale
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isDirectScriptRun } from './lib/is-direct-run';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/** Source → constant. The compose is the desktop-resource copy: the pull-only variant an appliance runs. */
export const BUNDLED_HUB_ASSET_SOURCES = {
  BUNDLED_HUB_COMPOSE: 'packages/desktop/src-tauri/resources/docker-compose.prod.yml',
  BUNDLED_TRAEFIK_YML: 'packages/backend/assets/traefik/traefik.yml',
  BUNDLED_TRAEFIK_DYNAMIC_YML: 'packages/backend/assets/traefik/dynamic/dynamic.yml',
  // The host GPU probe `cihub fleet` installs on each node (scripts/lib/gpu-probe-timer.ts). Bundled
  // for the same reason as the compose: the operator's `cihub` may be the standalone binary.
  BUNDLED_GPU_PROBE_SCRIPT: 'scripts/host-probes/cihub-gpu-processes.sh',
  BUNDLED_GPU_PROBE_SERVICE: 'scripts/host-probes/cihub-gpu-processes.service',
  BUNDLED_GPU_PROBE_TIMER: 'scripts/host-probes/cihub-gpu-processes.timer',
} as const;

export const BUNDLED_HUB_ASSETS_MODULE = 'scripts/lib/bundled-hub-assets.generated.ts';

export function renderBundledHubAssetsModule(repoRoot = REPO_ROOT): string {
  const entries = Object.entries(BUNDLED_HUB_ASSET_SOURCES).map(
    ([name, rel]) => [name, rel, readFileSync(path.join(repoRoot, rel), 'utf8')] as const,
  );
  const digest = createHash('sha256');
  for (const [, , content] of entries) digest.update(content);
  const lines = [
    '// GENERATED by scripts/generate-bundled-hub-assets.ts — do not edit. `pnpm run build:cli` regenerates it;',
    '// scripts/__tests__/bundled-hub-assets.test.ts fails when it drifts from its sources.',
    '',
    `export const BUNDLED_HUB_ASSETS_SHA256 = '${digest.digest('hex')}';`,
    '',
  ];
  for (const [name, rel, content] of entries) {
    lines.push(`/** ${rel} */`, `export const ${name} = ${JSON.stringify(content)};`, '');
  }
  return lines.join('\n');
}

export function bundledHubAssetsModuleIsCurrent(repoRoot = REPO_ROOT): boolean {
  const target = path.join(repoRoot, BUNDLED_HUB_ASSETS_MODULE);
  return existsSync(target) && readFileSync(target, 'utf8') === renderBundledHubAssetsModule(repoRoot);
}

if (isDirectScriptRun(import.meta.url, import.meta.main)) {
  const check = process.argv.includes('--check');
  if (check) {
    if (bundledHubAssetsModuleIsCurrent()) {
      console.log(`${BUNDLED_HUB_ASSETS_MODULE} is current`);
    } else {
      console.error(`${BUNDLED_HUB_ASSETS_MODULE} is stale — run: pnpm exec tsx scripts/generate-bundled-hub-assets.ts`);
      process.exit(1);
    }
  } else {
    writeFileSync(path.join(REPO_ROOT, BUNDLED_HUB_ASSETS_MODULE), renderBundledHubAssetsModule());
    console.log(`wrote ${BUNDLED_HUB_ASSETS_MODULE}`);
  }
}
