name: Tipi CI
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - develop

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Install dependencies
        uses: "./.github/actions/install-dependencies"

      - name: Run biome tests
        run: pnpm run lint:ci

      - name: Run tsc
        run: pnpm run tsc

      - name: Run tests
        run: pnpm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: "./.github/actions/install-dependencies"

      - name: Build client
        run: pnpm run bundle
